package com.example.ui.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import com.example.data.model.AppLanguage

/**
 * Unified, strongly-typed localization string catalog for Ekikrit (एकीकृत).
 * Supports English, हिन्दी, ଓଡ଼ିଆ, and गोंडी (Beta).
 */
class AppStrings(private val map: Map<String, String>) {
    private fun get(key: String): String = map[key] ?: ""
    val languageCode: String get() = get("languageCode")

    // --- Core Branding & Top Bar ---
    val appTitle: String get() = get("appTitle")
    val portalSubtitle: String get() = get("portalSubtitle")
    val ministryName: String get() = get("ministryName")
    val studentMode: String get() = get("studentMode")
    val reviewerDeskMode: String get() = get("reviewerDeskMode")
    val appGuide: String get() = get("appGuide")
    val securityMenu: String get() = get("securityMenu")
    val auditTrailMenu: String get() = get("auditTrailMenu")
    val languageMenu: String get() = get("languageMenu")
    val replayTourMenu: String get() = get("replayTourMenu")
    val resetDemoMenu: String get() = get("resetDemoMenu")
    val selectLanguageTitle: String get() = get("selectLanguageTitle")
    val selectLanguageSubtitle: String get() = get("selectLanguageSubtitle")
    val currentLanguageBadge: String get() = get("currentLanguageBadge")
    val roleSwitchOfficer: String get() = get("roleSwitchOfficer")
    val roleSwitchStudent: String get() = get("roleSwitchStudent")
    val unreadNotifications: String get() = get("unreadNotifications")

    // --- Navigation Tabs ---
    val tabDashboard: String get() = get("tabDashboard")
    val tabSchemes: String get() = get("tabSchemes")
    val tabWallet: String get() = get("tabWallet")
    val tabDbtRail: String get() = get("tabDbtRail")
    val tabReviewDesk: String get() = get("tabReviewDesk")

    // --- Common Buttons & Controls ---
    val close: String get() = get("close")
    val cancel: String get() = get("cancel")
    val applyNow: String get() = get("applyNow")
    val applied: String get() = get("applied")
    val viewDetails: String get() = get("viewDetails")
    val viewTimeline: String get() = get("viewTimeline")
    val askJago: String get() = get("askJago")
    val save: String get() = get("save")
    val submit: String get() = get("submit")
    val confirm: String get() = get("confirm")
    val back: String get() = get("back")
    val next: String get() = get("next")
    val finish: String get() = get("finish")
    val skip: String get() = get("skip")
    val retry: String get() = get("retry")
    val refresh: String get() = get("refresh")
    val searchPlaceholder: String get() = get("searchPlaceholder")
    val clearSearch: String get() = get("clearSearch")
    val switchUser: String get() = get("switchUser")

    // --- Dashboard & Hero Profile ---
    val welcomePrefix: String get() = get("welcomePrefix")
    val nspPfmsActive: String get() = get("nspPfmsActive")
    val portalName: String get() = get("portalName")
    val pvtgBadge: String get() = get("pvtgBadge")
    val aadhaarVerified: String get() = get("aadhaarVerified")
    val apaarIdLabel: String get() = get("apaarIdLabel")
    val institutionLabel: String get() = get("institutionLabel")
    val courseLabel: String get() = get("courseLabel")
    val annualIncomeLabel: String get() = get("annualIncomeLabel")
    val statDisbursed: String get() = get("statDisbursed")
    val statInPipeline: String get() = get("statInPipeline")
    val statDigiLocker: String get() = get("statDigiLocker")
    val zeroPaperwork: String get() = get("zeroPaperwork")
    val disbursedCardTitle: String get() = get("disbursedCardTitle")
    val eligibleSchemesTitle: String get() = get("eligibleSchemesTitle")
    val liveApplicationStatus: String get() = get("liveApplicationStatus")
    val dbtPaymentsSubtitle: String get() = get("dbtPaymentsSubtitle")
    val verificationSummary: String get() = get("verificationSummary")

    // --- Dashboard Banners & Cards ---
    val offlineBannerTitle: String get() = get("offlineBannerTitle")
    val offlineBannerDesc: String get() = get("offlineBannerDesc")
    val syncNowBtn: String get() = get("syncNowBtn")
    val unreachedBannerTitle: String get() = get("unreachedBannerTitle")
    val unreachedBannerDesc: String get() = get("unreachedBannerDesc")
    val unreachedActionBtn: String get() = get("unreachedActionBtn")
    val voiceAssistTitle: String get() = get("voiceAssistTitle")
    val voiceAssistDesc: String get() = get("voiceAssistDesc")
    val voiceAssistPlaying: String get() = get("voiceAssistPlaying")
    val voiceAssistPaused: String get() = get("voiceAssistPaused")
    val voiceAssistUnavailable: String get() = get("voiceAssistUnavailable")
    val voiceAssistSummaryDefault: String get() = get("voiceAssistSummaryDefault")
    val voiceAssistActiveSubtitle: String get() = get("voiceAssistActiveSubtitle")
    val voiceAssistTapToEnable: String get() = get("voiceAssistTapToEnable")
    val voiceAssistPause: String get() = get("voiceAssistPause")
    val voiceAssistListenAloud: String get() = get("voiceAssistListenAloud")
    val voiceAssistSpeaksDescription: String get() = get("voiceAssistSpeaksDescription")
    val pendingActionTitle: String get() = get("pendingActionTitle")
    val pendingActionIncomeDesc: String get() = get("pendingActionIncomeDesc")
    val resolveDiscrepancyBtn: String get() = get("resolveDiscrepancyBtn")
    val activeApplicationsTitle: String get() = get("activeApplicationsTitle")
    val activeApplicationsSubtitle: String get() = get("activeApplicationsSubtitle")
    val verificationChecklistTitle: String get() = get("verificationChecklistTitle")
    val verificationChecklistSubtitle: String get() = get("verificationChecklistSubtitle")
    val quickActionsTitle: String get() = get("quickActionsTitle")
    val quickActionWizard: String get() = get("quickActionWizard")
    val quickActionDigiLocker: String get() = get("quickActionDigiLocker")
    val quickActionTrack: String get() = get("quickActionTrack")
    val quickActionAskJago: String get() = get("quickActionAskJago")

    // --- Scheme Catalog & Filters ---
    val schemesHeaderTitle: String get() = get("schemesHeaderTitle")
    val schemesHeaderSubtitle: String get() = get("schemesHeaderSubtitle")
    val filterAll: String get() = get("filterAll")
    val filterPreMatric: String get() = get("filterPreMatric")
    val filterPostMatric: String get() = get("filterPostMatric")
    val filterTopClass: String get() = get("filterTopClass")
    val filterFellowship: String get() = get("filterFellowship")
    val filterOverseas: String get() = get("filterOverseas")
    val filterEligible: String get() = get("filterEligible")
    val filterApplied: String get() = get("filterApplied")
    val filterNeedsAttention: String get() = get("filterNeedsAttention")
    val filterNeedsAction: String get() = get("filterNeedsAction")
    val filterApproved: String get() = get("filterApproved")
    val filterInProgress: String get() = get("filterInProgress")
    val matchScoreLabel: String get() = get("matchScoreLabel")
    val grantAmountLabel: String get() = get("grantAmountLabel")
    val deadlineLabel: String get() = get("deadlineLabel")
    val deadlineDate: String get() = get("deadlineDate")
    val eligibilityCheckPassed: String get() = get("eligibilityCheckPassed")
    val noSchemesFound: String get() = get("noSchemesFound")

    // --- Scheme Detail Screen ---
    val schemeOverviewTitle: String get() = get("schemeOverviewTitle")
    val statutoryBenefitsTitle: String get() = get("statutoryBenefitsTitle")
    val eligibilityCriteriaTitle: String get() = get("eligibilityCriteriaTitle")
    val requiredDocumentsTitle: String get() = get("requiredDocumentsTitle")
    val verificationAuthorityTitle: String get() = get("verificationAuthorityTitle")
    val singleWindowNotice: String get() = get("singleWindowNotice")
    val oneClickApplyBanner: String get() = get("oneClickApplyBanner")
    val trackStatusTab: String get() = get("trackStatusTab")
    val noDisbursementsFound: String get() = get("noDisbursementsFound")

    // --- Scholarship Wizard Modal ---
    val wizardTitle: String get() = get("wizardTitle")
    val wizardStep1Title: String get() = get("wizardStep1Title")
    val wizardStep1Subtitle: String get() = get("wizardStep1Subtitle")
    val wizardStep2Title: String get() = get("wizardStep2Title")
    val wizardStep2Subtitle: String get() = get("wizardStep2Subtitle")
    val wizardStep3Title: String get() = get("wizardStep3Title")
    val wizardStep3Subtitle: String get() = get("wizardStep3Subtitle")
    val wizardStep4Title: String get() = get("wizardStep4Title")
    val wizardStep4Subtitle: String get() = get("wizardStep4Subtitle")
    val wizardIncomePrompt: String get() = get("wizardIncomePrompt")
    val wizardDocFetchSuccess: String get() = get("wizardDocFetchSuccess")
    val wizardDpdpConsentPrompt: String get() = get("wizardDpdpConsentPrompt")
    val wizardSubmitting: String get() = get("wizardSubmitting")
    val wizardSuccessTitle: String get() = get("wizardSuccessTitle")
    val wizardSuccessDesc: String get() = get("wizardSuccessDesc")

    // --- DigiLocker Wallet Screen & Modal ---
    val digiLockerWalletTitle: String get() = get("digiLockerWalletTitle")
    val digiLockerWalletSubtitle: String get() = get("digiLockerWalletSubtitle")
    val digiLockerConnected: String get() = get("digiLockerConnected")
    val digiLockerNotConnected: String get() = get("digiLockerNotConnected")
    val connectDigiLockerBtn: String get() = get("connectDigiLockerBtn")
    val syncCredentialsBtn: String get() = get("syncCredentialsBtn")
    val fetchMoreDocsBtn: String get() = get("fetchMoreDocsBtn")
    val zeroPaperworkGuarantee: String get() = get("zeroPaperworkGuarantee")
    val attachedCredentialsTitle: String get() = get("attachedCredentialsTitle")
    val tapToInspect: String get() = get("tapToInspect")
    val reusableBadge: String get() = get("reusableBadge")
    val digiLockerModalTitle: String get() = get("digiLockerModalTitle")
    val digiLockerConsentText: String get() = get("digiLockerConsentText")
    val digiLockerLinkSuccess: String get() = get("digiLockerLinkSuccess")
    val sealVerifiedText: String get() = get("sealVerifiedText")

    // --- DBT Disbursement Rail ---
    val dbtTrackerTitle: String get() = get("dbtTrackerTitle")
    val dbtTrackerSubtitle: String get() = get("dbtTrackerSubtitle")
    val dbtDisbursementsTitle: String get() = get("dbtDisbursementsTitle")
    val totalDisbursedLabel: String get() = get("totalDisbursedLabel")
    val inPipelineLabel: String get() = get("inPipelineLabel")
    val upcomingDisbursementsTitle: String get() = get("upcomingDisbursementsTitle")
    val completedDisbursementsTitle: String get() = get("completedDisbursementsTitle")
    val dbtAadhaarSeeded: String get() = get("dbtAadhaarSeeded")
    val dbtPfmsValidated: String get() = get("dbtPfmsValidated")
    val dbtCurrentTrancheTitle: String get() = get("dbtCurrentTrancheTitle")
    val dbtEstimatedDays: String get() = get("dbtEstimatedDays")
    val dbtPastTransfersTitle: String get() = get("dbtPastTransfersTitle")
    val dbtUtrLabel: String get() = get("dbtUtrLabel")
    val dbtAccountMaskedLabel: String get() = get("dbtAccountMaskedLabel")
    val dbtDirectBenefitGuarantee: String get() = get("dbtDirectBenefitGuarantee")

    // --- Reviewer Desk (Officer) ---
    val reviewerTitle: String get() = get("reviewerTitle")
    val reviewerSubtitle: String get() = get("reviewerSubtitle")
    val reviewerDeskTitle: String get() = get("reviewerDeskTitle")
    val reviewerDeskSubtitle: String get() = get("reviewerDeskSubtitle")
    val reviewerQueueAll: String get() = get("reviewerQueueAll")
    val reviewerQueuePending: String get() = get("reviewerQueuePending")
    val reviewerQueueResolved: String get() = get("reviewerQueueResolved")
    val reviewerDiscrepancyTitle: String get() = get("reviewerDiscrepancyTitle")
    val reviewerDeclaredValue: String get() = get("reviewerDeclaredValue")
    val reviewerRetrievedValue: String get() = get("reviewerRetrievedValue")
    val reviewerToleranceCheck: String get() = get("reviewerToleranceCheck")
    val reviewerTolerancePassed: String get() = get("reviewerTolerancePassed")
    val reviewerToleranceExceeded: String get() = get("reviewerToleranceExceeded")
    val reviewerApproveBtn: String get() = get("reviewerApproveBtn")
    val reviewerClarifyBtn: String get() = get("reviewerClarifyBtn")
    val reviewerNotesPlaceholder: String get() = get("reviewerNotesPlaceholder")
    val reviewerEmptyQueue: String get() = get("reviewerEmptyQueue")

    // --- Audit Trail & DPDP Compliance ---
    val auditTrailTitle: String get() = get("auditTrailTitle")
    val auditTrailSubtitle: String get() = get("auditTrailSubtitle")
    val auditTimestampLabel: String get() = get("auditTimestampLabel")
    val auditActorLabel: String get() = get("auditActorLabel")
    val auditPurposeLabel: String get() = get("auditPurposeLabel")
    val auditHashLabel: String get() = get("auditHashLabel")
    val dpdpModalTitle: String get() = get("dpdpModalTitle")
    val dpdpModalSubtitle: String get() = get("dpdpModalSubtitle")
    val dpdpDataMinimization: String get() = get("dpdpDataMinimization")
    val dpdpPurposeLimitation: String get() = get("dpdpPurposeLimitation")
    val dpdpConsentRevocation: String get() = get("dpdpConsentRevocation")
    val dpdpRightToErasure: String get() = get("dpdpRightToErasure")

    // --- Login & Personas ---
    val loginTitle: String get() = get("loginTitle")
    val loginSubtitle: String get() = get("loginSubtitle")
    val loginMobilePlaceholder: String get() = get("loginMobilePlaceholder")
    val loginSendOtpBtn: String get() = get("loginSendOtpBtn")
    val loginOtpPlaceholder: String get() = get("loginOtpPlaceholder")
    val loginVerifyBtn: String get() = get("loginVerifyBtn")
    val loginMockOtpHire: String get() = get("loginMockOtpHire")
    val loginPersonaQuickPicker: String get() = get("loginPersonaQuickPicker")
    val loginCustomStudentName: String get() = get("loginCustomStudentName")
    val loginLoggingIn: String get() = get("loginLoggingIn")

    // --- App Intro Tour ---
    val tourStep1Title: String get() = get("tourStep1Title")
    val tourStep1Desc: String get() = get("tourStep1Desc")
    val tourStep2Title: String get() = get("tourStep2Title")
    val tourStep2Desc: String get() = get("tourStep2Desc")
    val tourStep3Title: String get() = get("tourStep3Title")
    val tourStep3Desc: String get() = get("tourStep3Desc")
    val tourStep4Title: String get() = get("tourStep4Title")
    val tourStep4Desc: String get() = get("tourStep4Desc")
    val tourMultilingualHonestBadge: String get() = get("tourMultilingualHonestBadge")

    // --- Notifications & Share ---
    val notificationsTitle: String get() = get("notificationsTitle")
    val notificationsEmpty: String get() = get("notificationsEmpty")
    val notificationsMarkAllRead: String get() = get("notificationsMarkAllRead")
    val shareAppTitle: String get() = get("shareAppTitle")
    val shareAppSubtitle: String get() = get("shareAppSubtitle")
    val shareAppCopyLink: String get() = get("shareAppCopyLink")
    val shareAppInviteText: String get() = get("shareAppInviteText")

    // --- JAGO AI Chatbot ---
    val jagoTitle: String get() = get("jagoTitle")
    val jagoSubtitle: String get() = get("jagoSubtitle")
    val jagoTyping: String get() = get("jagoTyping")
    val jagoOfflineNotice: String get() = get("jagoOfflineNotice")
    val jagoInputPlaceholder: String get() = get("jagoInputPlaceholder")
    val askJagoPlaceholder: String get() = get("askJagoPlaceholder")
    val jagoSendBtn: String get() = get("jagoSendBtn")
    val jagoWelcomeMessage: String get() = get("jagoWelcomeMessage")
    val jagoLanguageSwitchOffer: String get() = get("jagoLanguageSwitchOffer")
    val jagoSwitchLanguageBtn: String get() = get("jagoSwitchLanguageBtn")
    val jagoChipStatus: String get() = get("jagoChipStatus")
    val jagoChipEligible: String get() = get("jagoChipEligible")
    val jagoChipDocs: String get() = get("jagoChipDocs")
    val jagoChipPayment: String get() = get("jagoChipPayment")
    val jagoChipIncomeFlag: String get() = get("jagoChipIncomeFlag")
    val jagoChipVariance: String get() = get("jagoChipVariance")
    val jagoChipApply: String get() = get("jagoChipApply")

    // --- Enums & Statuses Localization ---
    val stageSubmitted: String get() = get("stageSubmitted")
    val stageInstituteVerification: String get() = get("stageInstituteVerification")
    val stageStateVerification: String get() = get("stageStateVerification")
    val stageMinistryReview: String get() = get("stageMinistryReview")
    val stageSanctioned: String get() = get("stageSanctioned")
    val stageDisbursed: String get() = get("stageDisbursed")
    val stageActionRequired: String get() = get("stageActionRequired")
    val stageRejected: String get() = get("stageRejected")

    val statusVerified: String get() = get("statusVerified")
    val statusMismatch: String get() = get("statusMismatch")
    val statusPending: String get() = get("statusPending")
    val statusResolved: String get() = get("statusResolved")
    val statusDiscrepancy: String get() = get("statusDiscrepancy")

    val docAadhaar: String get() = get("docAadhaar")
    val docCaste: String get() = get("docCaste")
    val docIncome: String get() = get("docIncome")
    val docMarksheet: String get() = get("docMarksheet")
    val docDomicile: String get() = get("docDomicile")
    val docApaar: String get() = get("docApaar")
    val docAdmissionProof: String get() = get("docAdmissionProof")
    val docFeeReceipt: String get() = get("docFeeReceipt")
    val docBankPassbook: String get() = get("docBankPassbook")

    val srcUidai: String get() = get("srcUidai")
    val srcDigilocker: String get() = get("srcDigilocker")
    val srcAishe: String get() = get("srcAishe")
    val srcApaar: String get() = get("srcApaar")
    val srcUdisePlus: String get() = get("srcUdisePlus")
    val srcUgcNta: String get() = get("srcUgcNta")
    val srcEdistrict: String get() = get("srcEdistrict")

    // --- Scheme Name & Desc Overrides ---
    val schemePreName: String get() = get("schemePreName")
    val schemePreDesc: String get() = get("schemePreDesc")
    val schemePmsName: String get() = get("schemePmsName")
    val schemePmsDesc: String get() = get("schemePmsDesc")
    val schemeTopClassName: String get() = get("schemeTopClassName")
    val schemeTopClassDesc: String get() = get("schemeTopClassDesc")
    val schemeNfstName: String get() = get("schemeNfstName")
    val schemeNfstDesc: String get() = get("schemeNfstDesc")
    val schemeNosName: String get() = get("schemeNosName")
    val schemeNosDesc: String get() = get("schemeNosDesc")
}
