package com.example.ui.util

val EnglishStrings = AppStrings(mapOf(
    "languageCode" to "en",

    // Core Branding & Top Bar
    "appTitle" to "Ekikrit",
    "portalSubtitle" to "Unified Tribal Scholarship Portal",
    "ministryName" to "Ministry of Tribal Affairs • Govt. of India",
    "studentMode" to "Student View",
    "reviewerDeskMode" to "Officer Review Desk",
    "appGuide" to "User Guide",
    "securityMenu" to "Security & DPDP Consent",
    "auditTrailMenu" to "Governance Audit Log",
    "languageMenu" to "App Language",
    "replayTourMenu" to "Replay App Intro Tour",
    "resetDemoMenu" to "Reset Demo Data",
    "selectLanguageTitle" to "Select App Language",
    "selectLanguageSubtitle" to "Instant switch • Works offline across all 5 schemes",
    "currentLanguageBadge" to "Active",
    "roleSwitchOfficer" to "Switch to Officer Desk",
    "roleSwitchStudent" to "Switch to Student View",
    "unreadNotifications" to "%1\$d new notifications",

    // Navigation Tabs
    "tabDashboard" to "Dashboard",
    "tabSchemes" to "5 Schemes",
    "tabWallet" to "Wallet",
    "tabDbtRail" to "DBT Rail",
    "tabReviewDesk" to "Review Desk",

    // Common Buttons & Controls
    "close" to "Close",
    "cancel" to "Cancel",
    "applyNow" to "Apply Now",
    "applied" to "Applied",
    "viewDetails" to "View details",
    "viewTimeline" to "View Timeline",
    "askJago" to "Ask JAGO",
    "save" to "Save",
    "submit" to "Submit Application",
    "confirm" to "Confirm & Proceed",
    "back" to "Back",
    "next" to "Next",
    "finish" to "Get Started",
    "skip" to "Skip Tour",
    "retry" to "Retry",
    "refresh" to "Refresh Data",
    "searchPlaceholder" to "Search schemes by keyword, course, or grant...",
    "clearSearch" to "Clear search",
    "switchUser" to "Switch Persona",

    // Dashboard & Hero Profile
    "welcomePrefix" to "Welcome back",
    "nspPfmsActive" to "NSP & PFMS Active",
    "portalName" to "Unified Tribal Scholarship Portal",
    "pvtgBadge" to "PVTG: Birhor",
    "aadhaarVerified" to "Aadhaar Verified",
    "apaarIdLabel" to "APAAR ID",
    "institutionLabel" to "Institution",
    "courseLabel" to "Course",
    "annualIncomeLabel" to "Family Income",
    "statDisbursed" to "Received",
    "statInPipeline" to "In Progress",
    "statDigiLocker" to "Saved Docs",
    "zeroPaperwork" to "0 Paperwork",
    "disbursedCardTitle" to "Total Disbursed",
    "eligibleSchemesTitle" to "Eligible Government Schemes",
    "liveApplicationStatus" to "Live Application Tracking",
    "dbtPaymentsSubtitle" to "Direct to Aadhaar-linked Bank Account",
    "verificationSummary" to "Multi-Registry Verification Summary",

    // Dashboard Banners & Cards
    "offlineBannerTitle" to "Offline Mode Active",
    "offlineBannerDesc" to "%1\$d draft applications queued locally. Will auto-sync when online.",
    "syncNowBtn" to "Sync Now",
    "unreachedBannerTitle" to "Unreached Beneficiary Outreach",
    "unreachedBannerDesc" to "Special assistance for PVTG and remote tribal settlements. No document re-upload required.",
    "unreachedActionBtn" to "Explore Special Grants",
    "voiceAssistTitle" to "Listen Aloud",
    "voiceAssistDesc" to "Tap to listen to your current scholarship summary in clear voice.",
    "voiceAssistPlaying" to "Reading screen summary...",
    "voiceAssistPaused" to "Speech paused",
    "voiceAssistUnavailable" to "Text-to-Speech voice not available for this language.",
    "voiceAssistSummaryDefault" to "Here is your unified tribal scholarship overview.",
    "voiceAssistActiveSubtitle" to "Voice mode enabled • Tap below to play",
    "voiceAssistTapToEnable" to "Tap switch to enable audio assistance",
    "voiceAssistPause" to "Pause",
    "voiceAssistListenAloud" to "Listen Aloud",
    "voiceAssistSpeaksDescription" to "Audio narration reads the current screen summary aloud in your selected language.",
    "pendingActionTitle" to "Needs Attention: Review Discrepancy",
    "pendingActionIncomeDesc" to "Income certificate difference noted. Officer review in progress under statutory tolerance.",
    "resolveDiscrepancyBtn" to "Track Review Status",
    "activeApplicationsTitle" to "Your Active Applications",
    "activeApplicationsSubtitle" to "Single-window multi-registry tracking",
    "verificationChecklistTitle" to "Unified Multi-Registry Verification",
    "verificationChecklistSubtitle" to "7 national databases linked seamlessly",
    "quickActionsTitle" to "Quick Actions",
    "quickActionWizard" to "1-Click Apply",
    "quickActionDigiLocker" to "DigiLocker",
    "quickActionTrack" to "Track DBT",
    "quickActionAskJago" to "Ask JAGO",

    // Scheme Catalog & Filters
    "schemesHeaderTitle" to "5 Unified Tribal Schemes",
    "schemesHeaderSubtitle" to "Ministry of Tribal Affairs statutory scholarship catalog",
    "filterAll" to "All Schemes (5)",
    "filterPreMatric" to "Pre-Matric",
    "filterPostMatric" to "Post-Matric",
    "filterTopClass" to "Top Class",
    "filterFellowship" to "NFST Fellowship",
    "filterOverseas" to "National Overseas",
    "filterEligible" to "Eligible",
    "filterApplied" to "Applied",
    "filterNeedsAttention" to "Needs Action",
    "filterNeedsAction" to "Needs Action",
    "filterApproved" to "Approved",
    "filterInProgress" to "In Progress",
    "matchScoreLabel" to "Match: %1\$d%%",
    "grantAmountLabel" to "Grant Amount",
    "deadlineLabel" to "Deadline",
    "deadlineDate" to "Apply before deadline",
    "eligibilityCheckPassed" to "Eligibility Verified",
    "noSchemesFound" to "No schemes matching your filter criteria.",

    // Scheme Detail Screen
    "schemeOverviewTitle" to "Scheme Overview & Guidelines",
    "statutoryBenefitsTitle" to "Statutory Financial Benefits",
    "eligibilityCriteriaTitle" to "Eligibility Checklist",
    "requiredDocumentsTitle" to "Required Verified Documents",
    "verificationAuthorityTitle" to "Designated Sanction Authority",
    "singleWindowNotice" to "Single-Window Direct Benefit Transfer (Section 7 Aadhaar Act compliant)",
    "oneClickApplyBanner" to "Pre-filled from DigiLocker & APAAR Registry. Zero manual upload needed.",
    "trackStatusTab" to "Track Status",
    "noDisbursementsFound" to "No disbursements yet",

    // Scholarship Wizard Modal
    "wizardTitle" to "1-Click Scholarship Application",
    "wizardStep1Title" to "Student & Academic Verification",
    "wizardStep1Subtitle" to "Pulled from AISHE and APAAR registries",
    "wizardStep2Title" to "Family & Income Declaration",
    "wizardStep2Subtitle" to "Pulled from State e-District Certificate",
    "wizardStep3Title" to "DigiLocker Document Verification",
    "wizardStep3Subtitle" to "Automated cryptographic verification",
    "wizardStep4Title" to "Review & Submit to PFMS",
    "wizardStep4Subtitle" to "Section 7 Aadhaar Act statutory consent",
    "wizardIncomePrompt" to "Verify or update your family annual income (₹):",
    "wizardDocFetchSuccess" to "%1\$s verified and attached via DigiLocker.",
    "wizardDpdpConsentPrompt" to "I grant statutory consent under DPDP Act 2023 for automated verification.",
    "wizardSubmitting" to "Submitting application to Ministry Portal...",
    "wizardSuccessTitle" to "Application Successfully Submitted!",
    "wizardSuccessDesc" to "Application ID: %1\$s. You can track multi-stage progress in real time.",

    // DigiLocker Wallet Screen & Modal
    "digiLockerWalletTitle" to "DigiLocker Document Wallet",
    "digiLockerWalletSubtitle" to "Zero-paperwork reusable digital credentials",
    "digiLockerConnected" to "DigiLocker Connected",
    "digiLockerNotConnected" to "DigiLocker Not Linked",
    "connectDigiLockerBtn" to "Connect DigiLocker",
    "syncCredentialsBtn" to "Sync Credentials",
    "fetchMoreDocsBtn" to "Fetch More Documents",
    "zeroPaperworkGuarantee" to "Reusable across all 5 MoTA schemes without paper scanning.",
    "attachedCredentialsTitle" to "Verified Credentials in Wallet",
    "tapToInspect" to "Tap credential card to inspect digital verification seal",
    "reusableBadge" to "Reusable 5/5 Schemes",
    "digiLockerModalTitle" to "DigiLocker Statutory Consent",
    "digiLockerConsentText" to "By linking DigiLocker, you authorize Ekikrit to fetch your official government certificates.",
    "digiLockerLinkSuccess" to "DigiLocker wallet successfully linked.",
    "sealVerifiedText" to "Cryptographically signed by %1\$s on %2\$s",

    // DBT Disbursement Rail
    "dbtTrackerTitle" to "DBT Payment Rails",
    "dbtTrackerSubtitle" to "Direct benefit transfers via Reserve Bank of India PFMS",
    "dbtDisbursementsTitle" to "DBT Payment Rails",
    "totalDisbursedLabel" to "Total Disbursed",
    "inPipelineLabel" to "In Pipeline",
    "upcomingDisbursementsTitle" to "Upcoming Disbursements",
    "completedDisbursementsTitle" to "Completed Payments",
    "dbtAadhaarSeeded" to "Aadhaar-Seeded NPCI Active",
    "dbtPfmsValidated" to "PFMS Bank Account Validated",
    "dbtCurrentTrancheTitle" to "Sanctioned & Upcoming Grants",
    "dbtEstimatedDays" to "~%1\$d Days to Bank Credit",
    "dbtPastTransfersTitle" to "Disbursement Transaction Passbook",
    "dbtUtrLabel" to "UTR Ref: %1\$s",
    "dbtAccountMaskedLabel" to "Account: %1\$s",
    "dbtDirectBenefitGuarantee" to "100% of funds deposit directly to student without intermediaries.",

    // Reviewer Desk (Officer)
    "reviewerTitle" to "Officer Review Desk",
    "reviewerSubtitle" to "District Tribal Welfare Officer Desk #4 • Sundargarh, Odisha",
    "reviewerDeskTitle" to "Verification Reviewer Desk",
    "reviewerDeskSubtitle" to "District Tribal Welfare Officer Desk",
    "reviewerQueueAll" to "All Cases (%1\$d)",
    "reviewerQueuePending" to "Active Exceptions (%1\$d)",
    "reviewerQueueResolved" to "Resolved Archive (%1\$d)",
    "reviewerDiscrepancyTitle" to "Discrepancy: %1\$s",
    "reviewerDeclaredValue" to "Student Declared: %1\$s",
    "reviewerRetrievedValue" to "Registry Vault: %1\$s",
    "reviewerToleranceCheck" to "Variance: +%1\$.1f%% (Ceiling: ₹2.50L)",
    "reviewerTolerancePassed" to "Tolerance Eligible (Under 15%% Rule)",
    "reviewerToleranceExceeded" to "Tolerance Exceeded — Review Required",
    "reviewerApproveBtn" to "Approve Exception",
    "reviewerClarifyBtn" to "Request Resubmission",
    "reviewerNotesPlaceholder" to "Add officer endorsement notes...",
    "reviewerEmptyQueue" to "All scheme exceptions resolved.",

    // Audit Trail & DPDP Compliance
    "auditTrailTitle" to "DPDP Act Governance Audit Trail",
    "auditTrailSubtitle" to "Tamper-evident log of data accesses & verifications",
    "auditTimestampLabel" to "Timestamp",
    "auditActorLabel" to "System / Actor",
    "auditPurposeLabel" to "Statutory Purpose",
    "auditHashLabel" to "Integrity Hash",
    "dpdpModalTitle" to "Data Protection & DPDP Act 2023",
    "dpdpModalSubtitle" to "Your fundamental data privacy rights under Indian law",
    "dpdpDataMinimization" to "Data Minimization: Only essential eligibility data is accessed.",
    "dpdpPurposeLimitation" to "Purpose Limitation: Records used strictly for scholarship disbursement.",
    "dpdpConsentRevocation" to "Right to Withdraw Consent: Revoke at any time.",
    "dpdpRightToErasure" to "Right to Grievance Redressal: Lodge complaints directly with the Data Protection Board.",

    // Login & Personas
    "loginTitle" to "Student Beneficiary Sign In",
    "loginSubtitle" to "Unified Access via Mobile Number or Aadhaar",
    "loginMobilePlaceholder" to "Enter 10-digit Mobile or 12-digit Aadhaar",
    "loginSendOtpBtn" to "Send OTP",
    "loginOtpPlaceholder" to "Enter 6-digit OTP",
    "loginVerifyBtn" to "Verify & Access Scholarships",
    "loginMockOtpHire" to "Demo Test OTP: 123456",
    "loginPersonaQuickPicker" to "Or select a demo student persona:",
    "loginCustomStudentName" to "Enter your full name",
    "loginLoggingIn" to "Verifying with UIDAI & DigiLocker...",

    // App Intro Tour
    "tourStep1Title" to "Welcome to Ekikrit (एकीकृत)",
    "tourStep1Desc" to "One single-window mobile platform for all 5 Ministry of Tribal Affairs scholarship schemes.",
    "tourStep2Title" to "Zero Paperwork DigiLocker Wallet",
    "tourStep2Desc" to "Pull your caste, income, and marksheet once. Reuse effortlessly across all scholarships.",
    "tourStep3Title" to "Automated Multi-Registry Verification",
    "tourStep3Desc" to "Seven national registries verify your credentials automatically. Non-blocking officer review for variances.",
    "tourStep4Title" to "Direct-to-Bank DBT Payments",
    "tourStep4Desc" to "Track PFMS payment sanctions directly to your Aadhaar-linked bank account in real time.",
    "tourMultilingualHonestBadge" to "Available in Hindi, Odia, Gondi (Beta), and English with voice readout.",

    // Notifications & Share
    "notificationsTitle" to "Notifications & Alerts",
    "notificationsEmpty" to "No new notifications",
    "notificationsMarkAllRead" to "Mark all read",
    "shareAppTitle" to "Share Ekikrit with Fellow Students",
    "shareAppSubtitle" to "Help tribal students in your village & college access government scholarships",
    "shareAppCopyLink" to "Copy App Link",
    "shareAppInviteText" to "Apply for Ministry of Tribal Affairs scholarships seamlessly on Ekikrit: https://ekikrit.tribal.gov.in",

    // JAGO AI Chatbot
    "jagoTitle" to "JAGO AI Assistant",
    "jagoSubtitle" to "Multilingual voice & text tribal scholarship guide",
    "jagoTyping" to "JAGO is thinking...",
    "jagoOfflineNotice" to "JAGO is running in offline guidance mode.",
    "jagoInputPlaceholder" to "Ask JAGO in Hindi, Odia, Gondi, English...",
    "askJagoPlaceholder" to "Ask JAGO anything in Hindi, Odia, Gondi, English...",
    "jagoSendBtn" to "Send",
    "jagoWelcomeMessage" to "Johar! I am JAGO, your Unified Tribal Scholarship Assistant. How may I help you today?",
    "jagoLanguageSwitchOffer" to "I detected you are typing in %1\$s. Would you like to switch app language to %2\$s?",
    "jagoSwitchLanguageBtn" to "Switch to %1\$s",
    "jagoChipStatus" to "Application Status",
    "jagoChipEligible" to "Which schemes can I apply for?",
    "jagoChipDocs" to "What documents do I need?",
    "jagoChipPayment" to "When will my scholarship arrive?",
    "jagoChipIncomeFlag" to "Why is my income flagged?",
    "jagoChipVariance" to "Why is my income flagged?",
    "jagoChipApply" to "How to apply in 1-click?",

    // Enums & Statuses Localization
    "stageSubmitted" to "Application Submitted",
    "stageInstituteVerification" to "Institute Verification",
    "stageStateVerification" to "State Verification",
    "stageMinistryReview" to "Ministry Sanction",
    "stageSanctioned" to "Grant Sanctioned",
    "stageDisbursed" to "Disbursed to Bank",
    "stageActionRequired" to "Needs Review",
    "stageRejected" to "Rejected",

    "statusVerified" to "Verified",
    "statusMismatch" to "Variance Flagged",
    "statusPending" to "Verification Pending",
    "statusResolved" to "Officer Cleared",
    "statusDiscrepancy" to "Needs Attention",

    "docAadhaar" to "Aadhaar Card",
    "docCaste" to "ST Caste Certificate",
    "docIncome" to "Income Certificate",
    "docMarksheet" to "Academic Marksheet",
    "docDomicile" to "Domicile Certificate",
    "docApaar" to "APAAR / ABC ID Card",
    "docAdmissionProof" to "Institute Admission Proof",
    "docFeeReceipt" to "Fee Payment Receipt",
    "docBankPassbook" to "Aadhaar Seeded Bank Passbook",

    "srcUidai" to "UIDAI Aadhaar Vault",
    "srcDigilocker" to "DigiLocker Digital Wallet",
    "srcAishe" to "AISHE Higher Education Portal",
    "srcApaar" to "APAAR One Nation ID",
    "srcUdisePlus" to "UDISE+ School Database",
    "srcUgcNta" to "UGC / NTA Portal",
    "srcEdistrict" to "State e-District Portal",

    // Scheme Name & Desc Overrides
    "schemePreName" to "Pre-Matric Scholarship for ST Students (Class IX & X)",
    "schemePreDesc" to "Financial assistance of ₹3,500/yr for ST students enrolled in secondary school.",
    "schemePmsName" to "Post-Matric Scholarship for ST Students",
    "schemePmsDesc" to "Comprehensive tuition and living allowance (up to ₹20,000/yr) for higher education.",
    "schemeTopClassName" to "National Fellowship and Scholarship for Higher Education (Top Class)",
    "schemeTopClassDesc" to "Full tuition and living stipend (up to ₹2,00,000/yr) for premier institutes (IIT/NIT/IIM/AIIMS).",
    "schemeNfstName" to "National Fellowship for ST Students (M.Phil / Ph.D)",
    "schemeNfstDesc" to "Monthly research fellowship of ₹31,000 to ₹35,000 for full-time doctoral scholars.",
    "schemeNosName" to "National Overseas Scholarship for ST Candidates",
    "schemeNosDesc" to "Full funding for master's and doctoral degrees abroad at top 500 QS global universities."
))
