package com.example.ui.util

val GondiStrings = AppStrings(mapOf(
    "languageCode" to "gon",

    // Core Branding & Top Bar
    "appTitle" to "एकीकृत",
    "portalSubtitle" to "गोंडी कोया छात्रवृत्ति पोर्टल (बीटा)",
    "ministryName" to "जनजातीय कार्य मंत्रालय • भारत सरकार",
    "studentMode" to "विद्यार्थी दृश्य",
    "reviewerDeskMode" to "अधिकारी समीक्षा डेस्क",
    "appGuide" to "सिक्के मार्गदर्शिका",
    "securityMenu" to "सुरक्षा व DPDP सहमति",
    "auditTrailMenu" to "पारदर्शिता ऑडिट लॉग",
    "languageMenu" to "ऐप भाषा",
    "replayTourMenu" to "ऐप टूर मरोम चूड़ा",
    "resetDemoMenu" to "डेमो डेटा रीसेट कीम",
    "selectLanguageTitle" to "ऐप ना भाषा रोसा",
    "selectLanguageSubtitle" to "तुरंत भाषा बदलो कीम • 5 योजनांग offline काम कींत",
    "currentLanguageBadge" to "सक्रिय",
    "roleSwitchOfficer" to "अधिकारी डेस्क ते दा",
    "roleSwitchStudent" to "विद्यार्थी दृश्य ते वा",
    "unreadNotifications" to "%1\$d पुना संदेश",

    // Navigation Tabs
    "tabDashboard" to "डैशबोर्ड",
    "tabSchemes" to "5 योजनांग",
    "tabWallet" to "वॉलेट",
    "tabDbtRail" to "DBT रेल",
    "tabReviewDesk" to "समीक्षा डेस्क",

    // Common Buttons & Controls
    "close" to "बंद कीम",
    "cancel" to "रद्द कीम",
    "applyNow" to "आवेदन कीम",
    "applied" to "आवेदन कीता",
    "viewDetails" to "विवरण चूड़ा",
    "viewTimeline" to "समयरेखा चूड़ा",
    "askJago" to "जागो नाहि पुसा",
    "save" to "सहेज कीम",
    "submit" to "आवेदन जमा कीम",
    "confirm" to "पक्का कीम",
    "back" to "पज्जा",
    "next" to "मुन्ने",
    "finish" to "सुरू कीम",
    "skip" to "टूर छोड़ कीम",
    "retry" to "मरोम कीम",
    "refresh" to "डेटा ताज़ा कीम",
    "searchPlaceholder" to "योजना, कोर्स या अनुदान नाहि हुड़का...",
    "clearSearch" to "खोज साफ़ कीम",
    "switchUser" to "विद्यार्थी बदलो कीम",

    // Dashboard & Hero Profile
    "welcomePrefix" to "जोहार",
    "nspPfmsActive" to "NSP व PFMS सक्रिय",
    "portalName" to "जनजातीय छात्रवृत्ति एकल खिड़की पोर्टल",
    "pvtgBadge" to "विशेष कमजोर जनजातीय समूह (PVTG): बिरहोर",
    "aadhaarVerified" to "आधार सत्यापित",
    "apaarIdLabel" to "APAAR आईडी",
    "institutionLabel" to "संस्था",
    "courseLabel" to "कोर्स",
    "annualIncomeLabel" to "कुटुंब ना आय",
    "statDisbursed" to "जमा रुपया",
    "statInPipeline" to "काम सुरू",
    "statDigiLocker" to "कागद पत्र",
    "zeroPaperwork" to "0 कागद पत्र",
    "disbursedCardTitle" to "सब्बू जमा रुपया",
    "eligibleSchemesTitle" to "सरकारी योजनांग",
    "liveApplicationStatus" to "लाइव आवेदन स्थिति",
    "dbtPaymentsSubtitle" to "सीधे आधार बैंक खाता ते",
    "verificationSummary" to "सत्यापन विवरण",

    // Dashboard Banners & Cards
    "offlineBannerTitle" to "ऑफलाइन मोड सक्रिय",
    "offlineBannerDesc" to "%1\$d आवेदन सुरक्षित मंदा। ऑनलाइन आयते अपने आप जमा आयंत।",
    "syncNowBtn" to "इक्केने सिंक कीम",
    "unreachedBannerTitle" to "विशेष सहायता योजना",
    "unreachedBannerDesc" to "PVTG व दूर ना विद्यार्थी ना काजे विशेष सहायता। 1-क्लिक ते आवेदन कीम।",
    "unreachedActionBtn" to "अनुदान चूड़ा",
    "voiceAssistTitle" to "केंजा",
    "voiceAssistDesc" to "छात्रवृत्ति ना विवरण केंजना काजे दबा कीम।",
    "voiceAssistPlaying" to "स्क्रीन विवरण केंजाना चालू मंदा...",
    "voiceAssistPaused" to "आवाज बंद कीता",
    "voiceAssistUnavailable" to "इ भाषा काजे आवाज उपलब्ध हिल्ले।",
    "voiceAssistSummaryDefault" to "इ मीवा एकीकृत जनजातीय छात्रवृत्ति ना विवरण आंदूर।",
    "voiceAssistActiveSubtitle" to "आवाज मोड चालू मंदा • केंजना काजे अड़े दब कीम",
    "voiceAssistTapToEnable" to "आवाज चालू कीना काजे बटन दब कीम",
    "voiceAssistPause" to "बंद कीम",
    "voiceAssistListenAloud" to "केंजा",
    "voiceAssistSpeaksDescription" to "स्क्रीन ना मुख बात गोंडी ते केंजाए कींत।",
    "pendingActionTitle" to "ध्यान सीम: कागद पत्र जांच चालू मंदा",
    "pendingActionIncomeDesc" to "आय प्रमाण पत्र ते फरक मंदा। अधिकारी समीक्षा कींतूर।",
    "resolveDiscrepancyBtn" to "स्थिति चूड़ा",
    "activeApplicationsTitle" to "मीवा चालू आवेदन",
    "activeApplicationsSubtitle" to "एकल खिड़की ट्रैकिंग",
    "verificationChecklistTitle" to "एकीकृत सत्यापन",
    "verificationChecklistSubtitle" to "7 राष्ट्रीय डेटाबेस से स्वतः सत्यापित",
    "quickActionsTitle" to "जल्दी काम",
    "quickActionWizard" to "1-क्लिक आवेदन",
    "quickActionDigiLocker" to "डिजीलॉकर",
    "quickActionTrack" to "DBT चूड़ा",
    "quickActionAskJago" to "जागो नाहि पुसा",

    // Scheme Catalog & Filters
    "schemesHeaderTitle" to "5 एकीकृत जनजातीय योजनांग",
    "schemesHeaderSubtitle" to "जनजातीय कार्य मंत्रालय सरकारी छात्रवृत्ति सूची",
    "filterAll" to "सब्बू योजनांग (5)",
    "filterPreMatric" to "प्री-मैट्रिक",
    "filterPostMatric" to "पोस्ट-मैट्रिक",
    "filterTopClass" to "टॉप क्लास",
    "filterFellowship" to "NFST फेलोशिप",
    "filterOverseas" to "राष्ट्रीय ओवरसीज",
    "filterEligible" to "पात्र",
    "filterApplied" to "आवेदन कीता",
    "filterNeedsAttention" to "समीक्षा जरूरी",
    "filterNeedsAction" to "समीक्षा जरूरी",
    "filterApproved" to "मंजूर",
    "filterInProgress" to "काम सुरू",
    "matchScoreLabel" to "योग्यता: %1\$d%%",
    "grantAmountLabel" to "अनुदान रुपया",
    "deadlineLabel" to "आखिरी तारीख",
    "deadlineDate" to "तारीख मुन्ने आवेदन कीम",
    "eligibilityCheckPassed" to "पात्रता पक्की",
    "noSchemesFound" to "इ श्रेणी ते योजना हिल्ले।",

    // Scheme Detail Screen
    "schemeOverviewTitle" to "योजना ना विवरण व नियम",
    "statutoryBenefitsTitle" to "वित्तीय लाभ",
    "eligibilityCriteriaTitle" to "पात्रता नियम",
    "requiredDocumentsTitle" to "जरूरी कागद पत्र",
    "verificationAuthorityTitle" to "मंजूरी अधिकारी",
    "singleWindowNotice" to "एकल खिड़की डायरेक्ट बेनिफिट ट्रांसफर (आधार एक्ट धारा 7)",
    "oneClickApplyBanner" to "डिजीलॉकर व अपार से भरा कीता। कागद अपलोड कीना जरूरी हिल्ले।",
    "trackStatusTab" to "स्थिति चूड़ा",
    "noDisbursementsFound" to "इंजेवर रुपया जमा आयि हिल्ले",

    // Scholarship Wizard Modal
    "wizardTitle" to "1-क्लिक छात्रवृत्ति आवेदन",
    "wizardStep1Title" to "विद्यार्थी व पढ़ाई जांच",
    "wizardStep1Subtitle" to "AISHE व APAAR डेटाबेस से वाता",
    "wizardStep2Title" to "कुटुंब व आय घोषणा",
    "wizardStep2Subtitle" to "ई-डिस्ट्रिक्ट पोर्टल से वाता",
    "wizardStep3Title" to "डिजीलॉकर कागद पत्र जांच",
    "wizardStep3Subtitle" to "डिजिटल मुहर से सत्यापित",
    "wizardStep4Title" to "समीक्षा व PFMS ते रोहना",
    "wizardStep4Subtitle" to "आधार एक्ट धारा 7 सहमति",
    "wizardIncomePrompt" to "कुटुंब ना वार्षिक आय पक्का कीम (₹):",
    "wizardDocFetchSuccess" to "%1\$s डिजीलॉकर से सत्यापित कीता।",
    "wizardDpdpConsentPrompt" to "नना DPDP Act 2023 ना तहत सत्यापन काजे सहमति सींतोन।",
    "wizardSubmitting" to "आवेदन मंत्रालय ते रोहना चालू मंदा...",
    "wizardSuccessTitle" to "आवेदन जमा आता!",
    "wizardSuccessDesc" to "आवेदन आईडी: %1\$s। स्थिति लाइव चूड़ा।",

    // DigiLocker Wallet Screen & Modal
    "digiLockerWalletTitle" to "डिजीलॉकर कागद वॉलेट",
    "digiLockerWalletSubtitle" to "कागद-रहित डिजिटल प्रमाण पत्र",
    "digiLockerConnected" to "डिजीलॉकर जुडता मंदा",
    "digiLockerNotConnected" to "डिजीलॉकर जुडे आयि हिल्ले",
    "connectDigiLockerBtn" to "डिजीलॉकर जोड़ कीम",
    "syncCredentialsBtn" to "प्रमाण पत्र सिंक कीम",
    "fetchMoreDocsBtn" to "पुना कागद रोसा",
    "zeroPaperworkGuarantee" to "सब्बू 5 योजनांग ते काम कींत, बिना स्कैनिंग के।",
    "attachedCredentialsTitle" to "वॉलेट ते सत्यापित प्रमाण पत्र",
    "tapToInspect" to "डिजिटल मुहर चूड़ना काजे कार्ड दब कीम",
    "reusableBadge" to "5/5 योजनांग ते मान्य",
    "digiLockerModalTitle" to "डिजीलॉकर सहमति",
    "digiLockerConsentText" to "डिजीलॉकर जोड़ कीते सरकारी प्रमाण पत्र अपने आप वांत।",
    "digiLockerLinkSuccess" to "डिजीलॉकर लिंक आता।",
    "sealVerifiedText" to "%1\$s से %2\$s ना सत्यापित",

    // DBT Disbursement Rail
    "dbtTrackerTitle" to "DBT भुगतान रेल",
    "dbtTrackerSubtitle" to "भारतीय रिजर्व बैंक PFMS प्रणाली से सीधे जमा",
    "dbtDisbursementsTitle" to "DBT भुगतान रेल",
    "totalDisbursedLabel" to "सब्बू जमा रुपया",
    "inPipelineLabel" to "काम सुरू",
    "upcomingDisbursementsTitle" to "वाइना रुपया",
    "completedDisbursementsTitle" to "जमा आता",
    "dbtAadhaarSeeded" to "आधार लिंक NPCI चालू मंदा",
    "dbtPfmsValidated" to "PFMS बैंक खाता सत्यापित",
    "dbtCurrentTrancheTitle" to "मंजूर आता व वाइना रुपया",
    "dbtEstimatedDays" to "~%1\$d दिन ते बैंक खाता ते वांत",
    "dbtPastTransfersTitle" to "पासबुक व लेनदेन इतिहास",
    "dbtUtrLabel" to "UTR नंबर: %1\$s",
    "dbtAccountMaskedLabel" to "खाता नंबर: %1\$s",
    "dbtDirectBenefitGuarantee" to "100% छात्रवृत्ति सीधे विद्यार्थी ना बैंक खाता ते जमा आयंत।",

    // Reviewer Desk (Officer)
    "reviewerTitle" to "अधिकारी समीक्षा डेस्क",
    "reviewerSubtitle" to "जिला जनजातीय कल्याण अधिकारी डेस्क #4 • सुंदरगढ़, ओडिशा",
    "reviewerDeskTitle" to "सत्यापन समीक्षा डेस्क",
    "reviewerDeskSubtitle" to "जिला जनजातीय कल्याण अधिकारी डेस्क",
    "reviewerQueueAll" to "सब्बू केस (%1\$d)",
    "reviewerQueuePending" to "समीक्षा केस (%1\$d)",
    "reviewerQueueResolved" to "सुलझाता केस (%1\$d)",
    "reviewerDiscrepancyTitle" to "फरक विवरण: %1\$s",
    "reviewerDeclaredValue" to "विद्यार्थी ना आय: %1\$s",
    "reviewerRetrievedValue" to "सरकारी रिकॉर्ड: %1\$s",
    "reviewerToleranceCheck" to "फरक: +%1\$.1f%% (अधिकतम सीमा: ₹2.50L)",
    "reviewerTolerancePassed" to "सीमा ना अंदर मंदा (15%% नियम)",
    "reviewerToleranceExceeded" to "सीमा बाहर मंदा — जांच जरूरी",
    "reviewerApproveBtn" to "मंजूर कीम",
    "reviewerClarifyBtn" to "विद्यार्थी नाहि पुसा",
    "reviewerNotesPlaceholder" to "अधिकारी ना टिप्पणी...",
    "reviewerEmptyQueue" to "सब्बू केस निपट आता।",

    // Audit Trail & DPDP Compliance
    "auditTrailTitle" to "DPDP Act ऑडिट ट्रेल",
    "auditTrailSubtitle" to "डेटा एक्सेस व सत्यापन ना पक्का रिकॉर्ड",
    "auditTimestampLabel" to "समय",
    "auditActorLabel" to "सिस्टम / अधिकारी",
    "auditPurposeLabel" to "उद्देश्य",
    "auditHashLabel" to "हैश कोड",
    "dpdpModalTitle" to "डेटा सुरक्षा व DPDP Act 2023",
    "dpdpModalSubtitle" to "भारतीय कानून ना तहत मीवा डेटा अधिकार",
    "dpdpDataMinimization" to "डेटा न्यूनीकरण: जरूरी डेटा मात्र उपयोग आयंत।",
    "dpdpPurposeLimitation" to "उद्देश्य सीमा: रिकॉर्ड छात्रवृत्ति काजे मात्र काम कींत।",
    "dpdpConsentRevocation" to "सहमति वापस कीना अधिकार: कभी भी सहमति वापस कीय परिंत।",
    "dpdpRightToErasure" to "शिकायत अधिकार: डेटा प्रोटेक्शन बोर्ड नाहि शिकायत कीम।",

    // Login & Personas
    "loginTitle" to "विद्यार्थी लॉगिन",
    "loginSubtitle" to "मोबाइल नंबर या आधार से लॉगिन कीम",
    "loginMobilePlaceholder" to "10-अंक मोबाइल या 12-अंक आधार सीम",
    "loginSendOtpBtn" to "OTP रोह कीम",
    "loginOtpPlaceholder" to "6-अंक OTP सीम",
    "loginVerifyBtn" to "सत्यापित कीम व छात्रवृत्ति चूड़ा",
    "loginMockOtpHire" to "डेमो टेस्ट OTP: 123456",
    "loginPersonaQuickPicker" to "या डेमो विद्यार्थी रोसा:",
    "loginCustomStudentName" to "मीवा पूरा नाम सीम",
    "loginLoggingIn" to "UIDAI व डिजीलॉकर से जांच चालू मंदा...",

    // App Intro Tour
    "tourStep1Title" to "एकीकृत (Ekikrit) ते मीवा स्वागत मंदा",
    "tourStep1Desc" to "जनजातीय कार्य मंत्रालय ना 5 छात्रवृत्ति योजनांग काजे एकल मोबाइल ऐप।",
    "tourStep2Title" to "कागद-रहित डिजीलॉकर वॉलेट",
    "tourStep2Desc" to "जाति, आय व अंकतालिका एक बार रोसा व सब्बू छात्रवृत्ति ते उपयोग कीम।",
    "tourStep3Title" to "अपने आप सत्यापन",
    "tourStep3Desc" to "सात राष्ट्रीय डेटाबेस सत्यापन कींत। फरक आयते भी आवेदन अड़कना हिल्ले।",
    "tourStep4Title" to "सीधे बैंक खाता ते DBT",
    "tourStep4Desc" to "PFMS मंजूरी व आधार लिंक बैंक खाता ते रुपया जमा ना लाइव ट्रैकिंग।",
    "tourMultilingualHonestBadge" to "हिंदी, उड़िया, गोंडी (बीटा) व अंग्रेजी ते आवाज सहायता संग मंदा।",

    // Notifications & Share
    "notificationsTitle" to "संदेश व सूचनांग",
    "notificationsEmpty" to "पुना संदेश हिल्ले",
    "notificationsMarkAllRead" to "सब्बू पढ़ता कीम",
    "shareAppTitle" to "साथी विद्यार्थी नाहि शेयर कीम",
    "shareAppSubtitle" to "गांव व कॉलेज ना जनजातीय विद्यार्थी नाहि सहायता कीम",
    "shareAppCopyLink" to "ऐप लिंक कॉपी कीम",
    "shareAppInviteText" to "जनजातीय छात्रवृत्ति काजे एकीकृत ऐप ते आवेदन कीम: https://ekikrit.tribal.gov.in",

    // JAGO AI Chatbot
    "jagoTitle" to "जागो (JAGO) AI सहायक",
    "jagoSubtitle" to "बहुभाषी आवाज व टेक्स्ट छात्रवृत्ति मार्गदर्शक",
    "jagoTyping" to "जागो विचार कींतूर...",
    "jagoOfflineNotice" to "जागो इंजे offline मोड ते काम कींतूर।",
    "jagoInputPlaceholder" to "हिंदी, उड़िया, गोंडी या अंग्रेजी ते पुसा...",
    "askJagoPlaceholder" to "जागो नाहि हिंदी, उड़िया, गोंडी या अंग्रेजी ते पुसा...",
    "jagoSendBtn" to "रोह कीम",
    "jagoWelcomeMessage" to "जोहार! नना जागो आंदोन, मीवा जनजातीय छात्रवृत्ति सहायक। इंजे नना मीवा बतल सहायता कीय परिंतोन?",
    "jagoLanguageSwitchOffer" to "मीवा लिखावट %1\$s ते मंदा। ऐप ना भाषा %2\$s ते बदलो कीना चाहींत का?",
    "jagoSwitchLanguageBtn" to "%1\$s ते बदलो कीम",
    "jagoChipStatus" to "आवेदन स्थिति",
    "jagoChipEligible" to "नना बोन योजना काजे पात्र आंदोन?",
    "jagoChipDocs" to "नाके बोन कागद पत्र चाहींत?",
    "jagoChipPayment" to "नावा छात्रवृत्ति बशके वांत?",
    "jagoChipIncomeFlag" to "नावा आय ते जांच बरी मंदा?",
    "jagoChipVariance" to "नावा आय ते जांच बरी मंदा?",
    "jagoChipApply" to "1-क्लिक ते आवेदन बहेन कीना?",

    // Enums & Statuses Localization
    "stageSubmitted" to "आवेदन जमा आता",
    "stageInstituteVerification" to "संस्था सत्यापन",
    "stageStateVerification" to "राज्य सत्यापन",
    "stageMinistryReview" to "मंत्रालय मंजूरी",
    "stageSanctioned" to "अनुदान मंजूर",
    "stageDisbursed" to "बैंक खाता ते जमा आता",
    "stageActionRequired" to "समीक्षा जरूरी",
    "stageRejected" to "रद्द आता",

    "statusVerified" to "सत्यापित",
    "statusMismatch" to "फरक मंदा",
    "statusPending" to "जांच बाकी",
    "statusResolved" to "अधिकारी मंजूर कीतूर",
    "statusDiscrepancy" to "समीक्षा जरूरी",

    "docAadhaar" to "आधार कार्ड",
    "docCaste" to "ST जाति प्रमाण पत्र",
    "docIncome" to "आय प्रमाण पत्र",
    "docMarksheet" to "अंकतालिका",
    "docDomicile" to "निवास प्रमाण पत्र",
    "docApaar" to "APAAR आईडी कार्ड",
    "docAdmissionProof" to "प्रवेश प्रमाण पत्र",
    "docFeeReceipt" to "फीस रसीद",
    "docBankPassbook" to "आधार लिंक बैंक पासबुक",

    "srcUidai" to "UIDAI आधार वॉल्ट",
    "srcDigilocker" to "डिजीलॉकर डिजिटल वॉलेट",
    "srcAishe" to "AISHE पोर्टल",
    "srcApaar" to "APAAR छात्र आईडी",
    "srcUdisePlus" to "UDISE+ स्कूल डेटाबेस",
    "srcUgcNta" to "UGC / NTA पोर्टल",
    "srcEdistrict" to "राज्य ई-डिस्ट्रिक्ट पोर्टल",

    // Scheme Name & Desc Overrides
    "schemePreName" to "ST विद्यार्थी काजे प्री-मैट्रिक छात्रवृत्ति (कक्षा IX व X)",
    "schemePreDesc" to "माध्यमिक स्कूल ते पढ़इना ST विद्यार्थी काजे ₹3,500/साल सहायता।",
    "schemePmsName" to "ST विद्यार्थी काजे पोस्ट-मैट्रिक छात्रवृत्ति",
    "schemePmsDesc" to "उच्च शिक्षा काजे फीस व खर्चा (₹20,000/साल तक)।",
    "schemeTopClassName" to "राष्ट्रीय फेलोशिप व छात्रवृत्ति (टॉप क्लास)",
    "schemeTopClassDesc" to "IIT, NIT, IIM, AIIMS काजे पूरा फीस व ₹2,00,000/साल सहायता।",
    "schemeNfstName" to "ST विद्यार्थी काजे राष्ट्रीय फेलोशिप (M.Phil / Ph.D)",
    "schemeNfstDesc" to "शोधार्थी काजे ₹31,000 से ₹35,000/महीना फेलोशिप।",
    "schemeNosName" to "ST काजे राष्ट्रीय ओवरसीज छात्रवृत्ति",
    "schemeNosDesc" to "विदेश ते टॉप 500 यूनिवर्सिटी ते पढ़ाई काजे पूरा खर्चा।"
))
