package com.example.ui.util

val HindiStrings = AppStrings(mapOf(
    "languageCode" to "hi",

    // Core Branding & Top Bar
    "appTitle" to "एकीकृत",
    "portalSubtitle" to "जनजातीय छात्रवृत्ति एकल खिड़की पोर्टल",
    "ministryName" to "जनजातीय कार्य मंत्रालय • भारत सरकार",
    "studentMode" to "छात्र दृश्य",
    "reviewerDeskMode" to "अधिकारी समीक्षा डेस्क",
    "appGuide" to "उपयोगकर्ता मार्गदर्शिका",
    "securityMenu" to "सुरक्षा और DPDP सहमति",
    "auditTrailMenu" to "पारदर्शिता ऑडिट लॉग",
    "languageMenu" to "ऐप भाषा",
    "replayTourMenu" to "ऐप परिचयात्मक टूर पुनः देखें",
    "resetDemoMenu" to "डेमो डेटा रीसेट करें",
    "selectLanguageTitle" to "ऐप की भाषा चुनें",
    "selectLanguageSubtitle" to "तुरंत भाषा बदलें • सभी 5 योजनाओं में ऑफलाइन उपलब्ध",
    "currentLanguageBadge" to "सक्रिय",
    "roleSwitchOfficer" to "अधिकारी डेस्क पर जाएं",
    "roleSwitchStudent" to "छात्र दृश्य पर लौटें",
    "unreadNotifications" to "%1\$d नई सूचनाएं",

    // Navigation Tabs
    "tabDashboard" to "डैशबोर्ड",
    "tabSchemes" to "5 योजनाएं",
    "tabWallet" to "वॉलेट",
    "tabDbtRail" to "DBT रेल",
    "tabReviewDesk" to "समीक्षा डेस्क",

    // Common Buttons & Controls
    "close" to "बंद करें",
    "cancel" to "रद्द करें",
    "applyNow" to "आवेदन करें",
    "applied" to "आवेदित",
    "viewDetails" to "विवरण देखें",
    "viewTimeline" to "समयरेखा देखें",
    "askJago" to "जागो से पूछें",
    "save" to "सहेजें",
    "submit" to "आवेदन जमा करें",
    "confirm" to "पुष्टि करें और आगे बढ़ें",
    "back" to "पीछे",
    "next" to "आगे",
    "finish" to "शुरू करें",
    "skip" to "टूर छोड़ें",
    "retry" to "पुनः प्रयास करें",
    "refresh" to "डेटा रीफ्रेश करें",
    "searchPlaceholder" to "कीवर्ड, पाठ्यक्रम या अनुदान राशि से खोजें...",
    "clearSearch" to "खोज साफ़ करें",
    "switchUser" to "उपयोगकर्ता बदलें",

    // Dashboard & Hero Profile
    "welcomePrefix" to "नमस्ते",
    "nspPfmsActive" to "NSP एवं PFMS सक्रिय",
    "portalName" to "जनजातीय छात्रवृत्ति एकल खिड़की पोर्टल",
    "pvtgBadge" to "विशेष रूप से कमजोर जनजातीय समूह (PVTG): बिरहोर",
    "aadhaarVerified" to "आधार सत्यापित",
    "apaarIdLabel" to "अपार (APAAR) आईडी",
    "institutionLabel" to "संस्थान",
    "courseLabel" to "पाठ्यक्रम",
    "annualIncomeLabel" to "पारिवारिक आय",
    "statDisbursed" to "प्राप्त राशि",
    "statInPipeline" to "प्रक्रियाधीन",
    "statDigiLocker" to "सहेजे गए दस्तावेज़",
    "zeroPaperwork" to "0 कागजी कार्रवाई",
    "disbursedCardTitle" to "कुल वितरित राशि",
    "eligibleSchemesTitle" to "पात्र सरकारी योजनाएं",
    "liveApplicationStatus" to "लाइव आवेदन स्थिति",
    "dbtPaymentsSubtitle" to "सीधे आधार से जुड़े बैंक खाते में",
    "verificationSummary" to "बहु-पंजीयन सत्यापन सारांश",

    // Dashboard Banners & Cards
    "offlineBannerTitle" to "ऑफलाइन मोड सक्रिय",
    "offlineBannerDesc" to "%1\$d ड्राफ्ट आवेदन स्थानीय रूप से सुरक्षित हैं। ऑनलाइन होने पर स्वतः सिंक होंगे।",
    "syncNowBtn" to "अभी सिंक करें",
    "unreachedBannerTitle" to "वंचित लाभार्थी सहायता योजना",
    "unreachedBannerDesc" to "PVTG एवं दूरदराज के छात्रों के लिए विशेष सहायता। बिना किसी अतिरिक्त कागजात के 1-क्लिक आवेदन।",
    "unreachedActionBtn" to "विशेष अनुदान देखें",
    "voiceAssistTitle" to "बोलकर सुनें",
    "voiceAssistDesc" to "अपनी छात्रवृत्ति का सारांश स्पष्ट आवाज़ में सुनने के लिए टैप करें।",
    "voiceAssistPlaying" to "स्क्रीन सारांश पढ़ा जा रहा है...",
    "voiceAssistPaused" to "आवाज़ रोक दी गई है",
    "voiceAssistUnavailable" to "इस भाषा के लिए टेक्स्ट-टू-स्पीच उपलब्ध नहीं है।",
    "voiceAssistSummaryDefault" to "यह आपकी एकीकृत जनजातीय छात्रवृत्ति का विवरण है।",
    "voiceAssistActiveSubtitle" to "आवाज़ मोड सक्रिय • सुनने के लिए नीचे टैप करें",
    "voiceAssistTapToEnable" to "ऑडियो सहायता सक्षम करने के लिए स्विच दबाएं",
    "voiceAssistPause" to "रोकें",
    "voiceAssistListenAloud" to "बोलकर सुनें",
    "voiceAssistSpeaksDescription" to "ऑडियो विवरण स्क्रीन की महत्वपूर्ण जानकारी आपकी चुनी हुई भाषा में पढ़कर सुनाता है।",
    "pendingActionTitle" to "ध्यान दें: दस्तावेज़ समीक्षाधीन",
    "pendingActionIncomeDesc" to "आय प्रमाण पत्र में भिन्नता पाई गई है। कल्याण अधिकारी द्वारा सांविधिक नियम के तहत समीक्षा जारी है।",
    "resolveDiscrepancyBtn" to "समीक्षा स्थिति देखें",
    "activeApplicationsTitle" to "आपके सक्रिय आवेदन",
    "activeApplicationsSubtitle" to "एकल खिड़की बहु-पंजीयन ट्रैकिंग",
    "verificationChecklistTitle" to "एकीकृत बहु-पंजीयन सत्यापन",
    "verificationChecklistSubtitle" to "7 राष्ट्रीय डेटाबेस से स्वतः सत्यापित",
    "quickActionsTitle" to "त्वरित क्रियाएं",
    "quickActionWizard" to "1-क्लिक आवेदन",
    "quickActionDigiLocker" to "डिजीलॉकर",
    "quickActionTrack" to "DBT ट्रैक करें",
    "quickActionAskJago" to "जागो से पूछें",

    // Scheme Catalog & Filters
    "schemesHeaderTitle" to "5 एकीकृत जनजातीय योजनाएं",
    "schemesHeaderSubtitle" to "जनजातीय कार्य मंत्रालय का आधिकारिक छात्रवृत्ति कैटलॉग",
    "filterAll" to "सभी योजनाएं (5)",
    "filterPreMatric" to "प्री-मैट्रिक",
    "filterPostMatric" to "पोस्ट-मैट्रिक",
    "filterTopClass" to "टॉप क्लास",
    "filterFellowship" to "NFST फेलोशिप",
    "filterOverseas" to "राष्ट्रीय ओवरसीज",
    "filterEligible" to "पात्र",
    "filterApplied" to "आवेदित",
    "filterNeedsAttention" to "कार्रवाई आवश्यक",
    "filterNeedsAction" to "कार्रवाई आवश्यक",
    "filterApproved" to "स्वीकृत",
    "filterInProgress" to "प्रक्रियाधीन",
    "matchScoreLabel" to "योग्यता: %1\$d%%",
    "grantAmountLabel" to "अनुदान राशि",
    "deadlineLabel" to "अंतिम तिथि",
    "deadlineDate" to "समय सीमा से पहले आवेदन करें",
    "eligibilityCheckPassed" to "पात्रता सत्यापित",
    "noSchemesFound" to "चयनित फ़िल्टर के लिए कोई योजना उपलब्ध नहीं है।",

    // Scheme Detail Screen
    "schemeOverviewTitle" to "योजना का संक्षिप्त विवरण एवं नियम",
    "statutoryBenefitsTitle" to "सांविधिक वित्तीय लाभ",
    "eligibilityCriteriaTitle" to "पात्रता मानदंड",
    "requiredDocumentsTitle" to "आवश्यक सत्यापित दस्तावेज़",
    "verificationAuthorityTitle" to "नामित स्वीकृति प्राधिकारी",
    "singleWindowNotice" to "एकल खिड़की प्रत्यक्ष लाभ अंतरण (आधार अधिनियम की धारा 7 के अनुरूप)",
    "oneClickApplyBanner" to "डिजीलॉकर एवं अपार रजिस्ट्री से स्वतः भरा हुआ। किसी मैनुअल अपलोड की आवश्यकता नहीं।",
    "trackStatusTab" to "स्थिति ट्रैक करें",
    "noDisbursementsFound" to "अभी तक कोई वितरण नहीं हुआ है",

    // Scholarship Wizard Modal
    "wizardTitle" to "1-क्लिक छात्रवृत्ति आवेदन",
    "wizardStep1Title" to "छात्र एवं शैक्षणिक सत्यापन",
    "wizardStep1Subtitle" to "AISHE और APAAR पंजीयन से प्राप्त",
    "wizardStep2Title" to "पारिवारिक एवं आय घोषणा",
    "wizardStep2Subtitle" to "राज्य ई-डिस्ट्रिक्ट पोर्टल से सत्यापित",
    "wizardStep3Title" to "डिजीलॉकर दस्तावेज़ सत्यापन",
    "wizardStep3Subtitle" to "क्रिप्टोग्राफिक डिजिटल मुहर द्वारा सत्यापित",
    "wizardStep4Title" to "समीक्षा एवं PFMS को अग्रेषित",
    "wizardStep4Subtitle" to "आधार अधिनियम की धारा 7 के तहत सहमति",
    "wizardIncomePrompt" to "अपनी पारिवारिक वार्षिक आय की पुष्टि करें (₹):",
    "wizardDocFetchSuccess" to "%1\$s डिजीलॉकर द्वारा सत्यापित एवं संलग्न।",
    "wizardDpdpConsentPrompt" to "मैं DPDP अधिनियम 2023 के तहत स्वतः सत्यापन हेतु सहमति देता/देती हूँ।",
    "wizardSubmitting" to "आवेदन मंत्रालय पोर्टल पर भेजा जा रहा है...",
    "wizardSuccessTitle" to "आवेदन सफलतापूर्वक जमा हो गया!",
    "wizardSuccessDesc" to "आवेदन आईडी: %1\$s। आप वास्तविक समय में स्थिति ट्रैक कर सकते हैं।",

    // DigiLocker Wallet Screen & Modal
    "digiLockerWalletTitle" to "डिजीलॉकर दस्तावेज़ वॉलेट",
    "digiLockerWalletSubtitle" to "कागजरहित पुनः प्रयोज्य डिजिटल प्रमाण पत्र",
    "digiLockerConnected" to "डिजीलॉकर जुड़ा हुआ है",
    "digiLockerNotConnected" to "डिजीलॉकर नहीं जुड़ा है",
    "connectDigiLockerBtn" to "डिजीलॉकर कनेक्ट करें",
    "syncCredentialsBtn" to "प्रमाण पत्र सिंक करें",
    "fetchMoreDocsBtn" to "अन्य दस्तावेज़ प्राप्त करें",
    "zeroPaperworkGuarantee" to "सभी 5 योजनाओं में पुनः उपयोग योग्य, बिना किसी स्कैनिंग के।",
    "attachedCredentialsTitle" to "वॉलेट में सत्यापित प्रमाण पत्र",
    "tapToInspect" to "डिजिटल मुहर देखने के लिए प्रमाण पत्र कार्ड पर टैप करें",
    "reusableBadge" to "5/5 योजनाओं में मान्य",
    "digiLockerModalTitle" to "डिजीलॉकर सांविधिक सहमति",
    "digiLockerConsentText" to "डिजीलॉकर जोड़कर आप एकीकृत पोर्टल को अपने आधिकारिक प्रमाण पत्र प्राप्त करने के लिए अधिकृत करते हैं।",
    "digiLockerLinkSuccess" to "डिजीलॉकर वॉलेट सफलतापूर्वक लिंक हो गया।",
    "sealVerifiedText" to "%1\$s द्वारा %2\$s को डिजिटल रूप से सत्यापित",

    // DBT Disbursement Rail
    "dbtTrackerTitle" to "DBT भुगतान रेल",
    "dbtTrackerSubtitle" to "भारतीय रिज़र्व बैंक PFMS प्रणाली द्वारा प्रत्यक्ष लाभ अंतरण",
    "dbtDisbursementsTitle" to "DBT भुगतान रेल",
    "totalDisbursedLabel" to "कुल वितरित राशि",
    "inPipelineLabel" to "प्रक्रियाधीन",
    "upcomingDisbursementsTitle" to "आगामी वितरण",
    "completedDisbursementsTitle" to "सफल भुगतान",
    "dbtAadhaarSeeded" to "आधार से जुड़ा NPCI सक्रिय",
    "dbtPfmsValidated" to "PFMS बैंक खाता सत्यापित",
    "dbtCurrentTrancheTitle" to "स्वीकृत एवं आगामी अनुदान",
    "dbtEstimatedDays" to "~%1\$d दिनों में बैंक खाते में",
    "dbtPastTransfersTitle" to "वितरण पासबुक एवं लेनदेन इतिहास",
    "dbtUtrLabel" to "UTR संदर्भ: %1\$s",
    "dbtAccountMaskedLabel" to "खाता संख्या: %1\$s",
    "dbtDirectBenefitGuarantee" to "100% छात्रवृत्ति बिना किसी बिचौलिए के सीधे छात्र के खाते में जमा होती है।",

    // Reviewer Desk (Officer)
    "reviewerTitle" to "अधिकारी समीक्षा डेस्क",
    "reviewerSubtitle" to "जिला जनजातीय कल्याण अधिकारी डेस्क #4 • सुंदरगढ़, ओडिशा",
    "reviewerDeskTitle" to "सत्यापन समीक्षा डेस्क",
    "reviewerDeskSubtitle" to "जिला जनजातीय कल्याण अधिकारी डेस्क",
    "reviewerQueueAll" to "सभी मामले (%1\$d)",
    "reviewerQueuePending" to "समीक्षाधीन मामले (%1\$d)",
    "reviewerQueueResolved" to "स्वीकृत/निस्तारित अभिलेख (%1\$d)",
    "reviewerDiscrepancyTitle" to "अंतर विवरण: %1\$s",
    "reviewerDeclaredValue" to "छात्र द्वारा घोषित: %1\$s",
    "reviewerRetrievedValue" to "पंजीयन पोर्टल रिकॉर्ड: %1\$s",
    "reviewerToleranceCheck" to "भिन्नता: +%1\$.1f%% (अधिकतम सीमा: ₹2.50L)",
    "reviewerTolerancePassed" to "सहनशीलता सीमा के अंतर्गत (15%% सांविधिक नियम)",
    "reviewerToleranceExceeded" to "सीमा से अधिक — विस्तृत जांच आवश्यक",
    "reviewerApproveBtn" to "भिन्नता स्वीकृत करें",
    "reviewerClarifyBtn" to "छात्र से स्पष्टीकरण मांगें",
    "reviewerNotesPlaceholder" to "अधिकारी समीक्षा टिप्पणी दर्ज करें...",
    "reviewerEmptyQueue" to "सभी छात्रवृत्ति विसंगतियां निस्तारित हो चुकी हैं।",

    // Audit Trail & DPDP Compliance
    "auditTrailTitle" to "DPDP अधिनियम शासन ऑडिट ट्रेल",
    "auditTrailSubtitle" to "डेटा एक्सेस एवं सत्यापन का छेड़छाड़-रहित रिकॉर्ड",
    "auditTimestampLabel" to "समय",
    "auditActorLabel" to "सिस्टम / प्राधिकारी",
    "auditPurposeLabel" to "सांविधिक उद्देश्य",
    "auditHashLabel" to "अखंडता हैश",
    "dpdpModalTitle" to "डेटा संरक्षण एवं DPDP अधिनियम 2023",
    "dpdpModalSubtitle" to "भारतीय कानून के तहत आपके मौलिक डेटा गोपनीयता अधिकार",
    "dpdpDataMinimization" to "डेटा न्यूनीकरण: केवल आवश्यक पात्रता डेटा ही एक्सेस किया जाता है।",
    "dpdpPurposeLimitation" to "उद्देश्य सीमा: रिकॉर्ड का उपयोग केवल छात्रवृत्ति वितरण के लिए होता है।",
    "dpdpConsentRevocation" to "सहमति वापस लेने का अधिकार: किसी भी समय सहमति वापस ले सकते हैं।",
    "dpdpRightToErasure" to "शिकायत निवारण अधिकार: डेटा संरक्षण बोर्ड के समक्ष सीधी शिकायत।",

    // Login & Personas
    "loginTitle" to "छात्र लाभार्थी लॉगिन",
    "loginSubtitle" to "मोबाइल नंबर या आधार द्वारा एकीकृत प्रवेश",
    "loginMobilePlaceholder" to "10-अंकीय मोबाइल या 12-अंकीय आधार दर्ज करें",
    "loginSendOtpBtn" to "OTP भेजें",
    "loginOtpPlaceholder" to "6-अंकीय OTP दर्ज करें",
    "loginVerifyBtn" to "सत्यापित करें और छात्रवृत्ति देखें",
    "loginMockOtpHire" to "डेमो परीक्षण OTP: 123456",
    "loginPersonaQuickPicker" to "या डेमो छात्र प्रोफ़ाइल चुनें:",
    "loginCustomStudentName" to "अपना पूरा नाम दर्ज करें",
    "loginLoggingIn" to "UIDAI और डिजीलॉकर से सत्यापन जारी...",

    // App Intro Tour
    "tourStep1Title" to "एकीकृत (Ekikrit) में आपका स्वागत है",
    "tourStep1Desc" to "जनजातीय कार्य मंत्रालय की सभी 5 छात्रवृत्ति योजनाओं के लिए एकल खिड़की मोबाइल ऐप।",
    "tourStep2Title" to "कागजरहित डिजीलॉकर वॉलेट",
    "tourStep2Desc" to "जाति, आय और अंकतालिका एक बार लाएं और सभी छात्रवृत्तियों में बिना दोबारा अपलोड किए उपयोग करें।",
    "tourStep3Title" to "स्वचालित बहु-पंजीयन सत्यापन",
    "tourStep3Desc" to "सात राष्ट्रीय डेटाबेस आपके विवरणों की स्वतः पुष्टि करते हैं। विसंगति होने पर भी आवेदन नहीं रुकता।",
    "tourStep4Title" to "सीधे बैंक खाते में DBT भुगतान",
    "tourStep4Desc" to "PFMS भुगतान स्वीकृति और आधार से जुड़े बैंक खाते में जमा होने की वास्तविक समय पर ट्रैकिंग।",
    "tourMultilingualHonestBadge" to "हिंदी, उड़िया, गोंडी (बीटा) और अंग्रेजी में ऑडियो सहायता के साथ उपलब्ध।",

    // Notifications & Share
    "notificationsTitle" to "सूचनाएं एवं अलर्ट",
    "notificationsEmpty" to "कोई नई सूचना नहीं है",
    "notificationsMarkAllRead" to "सभी को पढ़ा हुआ चिह्नित करें",
    "shareAppTitle" to "साथी छात्रों के साथ एकीकृत साझा करें",
    "shareAppSubtitle" to "अपने गाँव और कॉलेज के जनजातीय छात्रों को छात्रवृत्ति प्राप्त करने में मदद करें",
    "shareAppCopyLink" to "ऐप लिंक कॉपी करें",
    "shareAppInviteText" to "जनजातीय कार्य मंत्रालय की छात्रवृत्ति के लिए एकीकृत ऐप पर सरलता से आवेदन करें: https://ekikrit.tribal.gov.in",

    // JAGO AI Chatbot
    "jagoTitle" to "जागो (JAGO) AI सहायक",
    "jagoSubtitle" to "बहुभाषी आवाज़ एवं टेक्स्ट जनजातीय छात्रवृत्ति मार्गदर्शक",
    "jagoTyping" to "जागो सोच रहा है...",
    "jagoOfflineNotice" to "जागो वर्तमान में ऑफलाइन मार्गदर्शन मोड में कार्य कर रहा है।",
    "jagoInputPlaceholder" to "हिंदी, उड़िया, गोंडी या अंग्रेजी में पूछें...",
    "askJagoPlaceholder" to "जागो से हिंदी, उड़िया, गोंडी या अंग्रेजी में कुछ भी पूछें...",
    "jagoSendBtn" to "भेजें",
    "jagoWelcomeMessage" to "जोहार! मैं जागो हूँ, आपका जनजातीय छात्रवृत्ति सहायक। आज मैं आपकी क्या सहायता कर सकता हूँ?",
    "jagoLanguageSwitchOffer" to "मैंने पाया कि आप %1\$s में लिख रहे हैं। क्या आप ऐप की भाषा %2\$s में बदलना चाहते हैं?",
    "jagoSwitchLanguageBtn" to "%1\$s में बदलें",
    "jagoChipStatus" to "आवेदन की स्थिति",
    "jagoChipEligible" to "मैं किन योजनाओं के लिए पात्र हूँ?",
    "jagoChipDocs" to "मुझे कौन से दस्तावेज़ चाहिए?",
    "jagoChipPayment" to "मेरी छात्रवृत्ति कब आएगी?",
    "jagoChipIncomeFlag" to "मेरी आय पर समीक्षा क्यों है?",
    "jagoChipVariance" to "मेरी आय पर समीक्षा क्यों है?",
    "jagoChipApply" to "1-क्लिक में आवेदन कैसे करें?",

    // Enums & Statuses Localization
    "stageSubmitted" to "आवेदन जमा हुआ",
    "stageInstituteVerification" to "संस्थान सत्यापन",
    "stageStateVerification" to "राज्य सत्यापन",
    "stageMinistryReview" to "मंत्रालय स्वीकृति",
    "stageSanctioned" to "अनुदान स्वीकृत",
    "stageDisbursed" to "बैंक खाते में अंतरित",
    "stageActionRequired" to "समीक्षा आवश्यक",
    "stageRejected" to "अस्वीकृत",

    "statusVerified" to "सत्यापित",
    "statusMismatch" to "भिन्नता चिह्नित",
    "statusPending" to "सत्यापन लंबित",
    "statusResolved" to "अधिकारी द्वारा स्वीकृत",
    "statusDiscrepancy" to "समीक्षाधीन",

    "docAadhaar" to "आधार कार्ड",
    "docCaste" to "अनुसूचित जनजाति जाति प्रमाण पत्र",
    "docIncome" to "आय प्रमाण पत्र",
    "docMarksheet" to "शैक्षणिक अंकतालिका",
    "docDomicile" to "मूल निवास प्रमाण पत्र",
    "docApaar" to "अपार / एबीसी आईडी कार्ड",
    "docAdmissionProof" to "संस्थान प्रवेश प्रमाण पत्र",
    "docFeeReceipt" to "फीस रसीद",
    "docBankPassbook" to "आधार लिंक बैंक पासबुक",

    "srcUidai" to "UIDAI आधार वॉल्ट",
    "srcDigilocker" to "डिजीलॉकर डिजिटल वॉलेट",
    "srcAishe" to "AISHE उच्च शिक्षा पोर्टल",
    "srcApaar" to "अपार (APAAR) छात्र आईडी",
    "srcUdisePlus" to "UDISE+ विद्यालय डेटाबेस",
    "srcUgcNta" to "UGC / NTA पोर्टल",
    "srcEdistrict" to "राज्य ई-डिस्ट्रिक्ट पोर्टल",

    // Scheme Name & Desc Overrides
    "schemePreName" to "अनुसूचित जनजाति छात्रों के लिए प्री-मैट्रिक छात्रवृत्ति (कक्षा IX एवं X)",
    "schemePreDesc" to "माध्यमिक विद्यालय में नामांकित ST छात्रों के लिए ₹3,500/वर्ष की वित्तीय सहायता।",
    "schemePmsName" to "अनुसूचित जनजाति छात्रों के लिए पोस्ट-मैट्रिक छात्रवृत्ति",
    "schemePmsDesc" to "उच्च शिक्षा हेतु पूर्ण शिक्षण शुल्क एवं जीवन निर्वाह भत्ता (₹20,000/वर्ष तक)।",
    "schemeTopClassName" to "उच्च शिक्षा हेतु राष्ट्रीय फेलोशिप एवं छात्रवृत्ति (टॉप क्लास)",
    "schemeTopClassDesc" to "आईआईटी, एनआईटी, आईआईएम, एम्स जैसे प्रतिष्ठित संस्थानों हेतु पूर्ण शुल्क एवं ₹2,00,000/वर्ष तक सहायता।",
    "schemeNfstName" to "अनुसूचित जनजाति छात्रों हेतु राष्ट्रीय फेलोशिप (एम.फिल / पीएच.डी)",
    "schemeNfstDesc" to "पूर्णकालिक डॉक्टरेट शोधार्थियों के लिए ₹31,000 से ₹35,000 प्रतिमाह की शोध फेलोशिप।",
    "schemeNosName" to "अनुसूचित जनजाति उम्मीदवारों हेतु राष्ट्रीय ओवरसीज छात्रवृत्ति",
    "schemeNosDesc" to "विश्व के शीर्ष 500 QS विश्वविद्यालयों में स्नातकोत्तर एवं डॉक्टरेट अध्ययन हेतु पूर्ण वित्तीय पोषण।"
))
