package com.example.ui.util

val OdiaStrings = AppStrings(mapOf(
    "languageCode" to "or",

    // Core Branding & Top Bar
    "appTitle" to "ଏକୀକୃତ",
    "portalSubtitle" to "ଜନଜାତି ଛାତ୍ରବୃତ୍ତି ଏକକ ପୋର୍ଟାଲ",
    "ministryName" to "ଜନଜାତି ବ୍ୟାପାର ମନ୍ତ୍ରଣାଳୟ • ଭାରତ ସରକାର",
    "studentMode" to "ଛାତ୍ର ମୋଡ୍",
    "reviewerDeskMode" to "ଅଧିକାରୀ ସମୀକ୍ଷା ଡେସ୍କ",
    "appGuide" to "ବ୍ୟବହାରକାରୀ ଗାଇଡ୍",
    "securityMenu" to "ସୁରକ୍ଷା ଓ DPDP ସମ୍ମତି",
    "auditTrailMenu" to "ସ୍ୱଚ୍ଛତା ଅଡିଟ୍ ଲଗ୍",
    "languageMenu" to "ଆପ୍ ଭାଷା",
    "replayTourMenu" to "ଆପ୍ ପରିଚୟ ଟୁର୍ ପୁନର୍ବାର ଦେଖନ୍ତୁ",
    "resetDemoMenu" to "ଡେମୋ ଡାଟା ରିସେଟ୍ କରନ୍ତୁ",
    "selectLanguageTitle" to "ଆପ୍ ଭାଷା ବାଛନ୍ତୁ",
    "selectLanguageSubtitle" to "ତୁରନ୍ତ ବଦଳାନ୍ତୁ • ସମସ୍ତ 5 ଯୋଜନାରେ ଅଫଲାଇନ୍ କାମ କରେ",
    "currentLanguageBadge" to "ସକ୍ରିୟ",
    "roleSwitchOfficer" to "ଅଧିକାରୀ ଡେସ୍କକୁ ଯାଆନ୍ତୁ",
    "roleSwitchStudent" to "ଛାତ୍ର ଦୃଶ୍ୟକୁ ଫେରନ୍ତୁ",
    "unreadNotifications" to "%1\$d ଟି ନୂଆ ବିଜ୍ଞପ୍ତି",

    // Navigation Tabs
    "tabDashboard" to "ଡ୍ୟାସବୋର୍ଡ",
    "tabSchemes" to "5 ଯୋଜନା",
    "tabWallet" to "ୱାଲେଟ୍",
    "tabDbtRail" to "DBT ରେଳ",
    "tabReviewDesk" to "ସମୀକ୍ଷା ଡେସ୍କ",

    // Common Buttons & Controls
    "close" to "ବନ୍ଦ କରନ୍ତୁ",
    "cancel" to "ବାତିଲ କରନ୍ତୁ",
    "applyNow" to "ଆବେଦନ କରନ୍ତୁ",
    "applied" to "ଆବେଦିତ",
    "viewDetails" to "ବିବରଣୀ ଦେଖନ୍ତୁ",
    "viewTimeline" to "ସମୟରେଖା ଦେଖନ୍ତୁ",
    "askJago" to "ଜାଗୋଙ୍କୁ ପଚାରନ୍ତୁ",
    "save" to "ସାଇତନ୍ତୁ",
    "submit" to "ଆବେଦନ ଦାଖଲ କରନ୍ତୁ",
    "confirm" to "ନିଶ୍ଚିତ କରନ୍ତୁ ଓ ଆଗକୁ ବଢ଼ନ୍ତୁ",
    "back" to "ପଛକୁ",
    "next" to "ପରବର୍ତ୍ତୀ",
    "finish" to "ଆରମ୍ଭ କରନ୍ତୁ",
    "skip" to "ଟୁର୍ ଛାଡନ୍ତୁ",
    "retry" to "ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ",
    "refresh" to "ତଥ୍ୟ ରିଫ୍ରେଶ କରନ୍ତୁ",
    "searchPlaceholder" to "କୀୱାର୍ଡ, ପାଠ୍ୟକ୍ରମ ବା ଅନୁଦାନ ରାଶି ଦ୍ୱାରା ଖୋଜନ୍ତୁ...",
    "clearSearch" to "ସନ୍ଧାନ ଖାଲି କରନ୍ତୁ",
    "switchUser" to "ବ୍ୟବହାରକାରୀ ବଦଳାନ୍ତୁ",

    // Dashboard & Hero Profile
    "welcomePrefix" to "ନମସ୍କାର",
    "nspPfmsActive" to "NSP ଓ PFMS ସକ୍ରିୟ",
    "portalName" to "ଜନଜାତି ଛାତ୍ରବୃତ୍ତି ଏକକ ପୋର୍ଟାଲ",
    "pvtgBadge" to "ବିଶେଷ ଭାବେ ଦୁର୍ବଳ ଜନଜାତି ଗୋଷ୍ଠୀ (PVTG): ବିରହୋର",
    "aadhaarVerified" to "ଆଧାର ପ୍ରମାଣିତ",
    "apaarIdLabel" to "APAAR ଆଇଡି",
    "institutionLabel" to "ଅନୁଷ୍ଠାନ",
    "courseLabel" to "ପାଠ୍ୟକ୍ରମ",
    "annualIncomeLabel" to "ପାରିବାରିକ ଆୟ",
    "statDisbursed" to "ପ୍ରାପ୍ତ ରାଶି",
    "statInPipeline" to "ପ୍ରକ୍ରିୟାଧୀନ",
    "statDigiLocker" to "ସଂରକ୍ଷିତ ଡକ୍ୟୁମେଣ୍ଟ",
    "zeroPaperwork" to "0 କାଗଜପତ୍ର କାର୍ଯ୍ୟ",
    "disbursedCardTitle" to "ମୋଟ ପ୍ରଦତ୍ତ ରାଶି",
    "eligibleSchemesTitle" to "ଯୋଗ୍ୟ ସରକାରୀ ଯୋଜନା",
    "liveApplicationStatus" to "ଲାଇଭ୍ ଆବେଦନ ସ୍ଥିତି",
    "dbtPaymentsSubtitle" to "ସିଧାସଳଖ ଆଧାର-ସଂଯୁକ୍ତ ବ୍ୟାଙ୍କ ଖାତାକୁ",
    "verificationSummary" to "ବହୁ-ପଞ୍ଜିକରଣ ଯାଞ୍ଚ ସାରାଂଶ",

    // Dashboard Banners & Cards
    "offlineBannerTitle" to "ଅଫଲାଇନ୍ ମୋଡ୍ ସକ୍ରିୟ",
    "offlineBannerDesc" to "%1\$d ଟି ଚିଠା ଆବେଦନ ସ୍ଥାନୀୟ ଭାବରେ ସଂରକ୍ଷିତ। ଅନଲାଇନ୍ ହେଲେ ସ୍ୱତଃ ସିଙ୍କ ହେବ।",
    "syncNowBtn" to "ବର୍ତ୍ତମାନ ସିଙ୍କ କରନ୍ତୁ",
    "unreachedBannerTitle" to "ବଞ୍ଚିତ ହିତାଧିକାରୀ ସହାୟତା ଯୋଜନା",
    "unreachedBannerDesc" to "PVTG ତଥା ଦୁର୍ଗମ ଅଞ୍ଚଳର ଛାତ୍ରଛାତ୍ରୀଙ୍କ ପାଇଁ ସ୍ୱତନ୍ତ୍ର ସହାୟତା। କୌଣସି ଅତିରିକ୍ତ କାଗଜପତ୍ର ବିନା 1-କ୍ଲିକ୍ ଆବେଦନ।",
    "unreachedActionBtn" to "ସ୍ୱତନ୍ତ୍ର ଅନୁଦାନ ଦେଖନ୍ତୁ",
    "voiceAssistTitle" to "ଶୁଣନ୍ତୁ",
    "voiceAssistDesc" to "ଆପଣଙ୍କ ଛାତ୍ରବୃତ୍ତିର ସାରାଂଶ ସ୍ପଷ୍ଟ ସ୍ୱରରେ ଶୁଣିବା ପାଇଁ ଟ୍ୟାପ୍ କରନ୍ତୁ।",
    "voiceAssistPlaying" to "ସ୍କ୍ରିନ୍ ସାରାଂଶ ପଢ଼ାଯାଉଛି...",
    "voiceAssistPaused" to "ସ୍ୱର ବନ୍ଦ କରାଯାଇଛି",
    "voiceAssistUnavailable" to "ଏହି ଭାଷା ପାଇଁ ଟେକ୍ସଟ୍-ଟୁ-ସ୍ପିଚ୍ ଉପଲବ୍ଧ ନାହିଁ।",
    "voiceAssistSummaryDefault" to "ଏହା ଆପଣଙ୍କ ଏକୀକୃତ ଜନଜାତି ଛାତ୍ରବୃତ୍ତିର ବିବରଣୀ।",
    "voiceAssistActiveSubtitle" to "ସ୍ୱର ମୋଡ୍ ସକ୍ରିୟ • ଶୁଣିବା ପାଇଁ ତଳେ ଟ୍ୟାପ୍ କରନ୍ତୁ",
    "voiceAssistTapToEnable" to "ଅଡିଓ ସହାୟତା ସକ୍ଷମ କରିବାକୁ ସୁଇଚ୍ ଦବାନ୍ତୁ",
    "voiceAssistPause" to "ବନ୍ଦ କରନ୍ତୁ",
    "voiceAssistListenAloud" to "ଶୁଣନ୍ତୁ",
    "voiceAssistSpeaksDescription" to "ଅଡିଓ ବିବରଣୀ ସ୍କ୍ରିନର ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ସୂଚନା ଆପଣଙ୍କ ପସନ୍ଦର ଭାଷାରେ ପଢ଼ି ଶୁଣାଏ।",
    "pendingActionTitle" to "ଧ୍ୟାନ ଦିଅନ୍ତୁ: ଡକ୍ୟୁମେଣ୍ଟ ସମୀକ୍ଷାଧୀନ",
    "pendingActionIncomeDesc" to "ଆୟ ପ୍ରମାଣପତ୍ରରେ ପାର୍ଥକ୍ୟ ଦେଖାଯାଇଛି। କଲ୍ୟାଣ ଅଧିକାରୀଙ୍କ ଦ୍ୱାରା ନିୟମ ଅନୁସାରେ ସମୀକ୍ଷା ଚାଲିଛି।",
    "resolveDiscrepancyBtn" to "ସମୀକ୍ଷା ସ୍ଥିତି ଦେଖନ୍ତୁ",
    "activeApplicationsTitle" to "ଆପଣଙ୍କ ସକ୍ରିୟ ଆବେଦନଗୁଡ଼ିକ",
    "activeApplicationsSubtitle" to "ଏକକ ୱିଣ୍ଡୋ ବହୁ-ପଞ୍ଜିକରଣ ଟ୍ରାକିଂ",
    "verificationChecklistTitle" to "ଏକୀକୃତ ବହୁ-ପଞ୍ଜିକରଣ ଯାଞ୍ଚ",
    "verificationChecklistSubtitle" to "7 ଟି ଜାତୀୟ ଡାଟାବେସ୍ ସହ ସ୍ୱତଃ ପ୍ରମାଣିତ",
    "quickActionsTitle" to "ଦ୍ରୁତ କାର୍ଯ୍ୟ",
    "quickActionWizard" to "1-କ୍ଲିକ୍ ଆବେଦନ",
    "quickActionDigiLocker" to "ଡିଜିଲକର",
    "quickActionTrack" to "DBT ଟ୍ରାକ୍ କରନ୍ତୁ",
    "quickActionAskJago" to "ଜାଗୋଙ୍କୁ ପଚାରନ୍ତୁ",

    // Scheme Catalog & Filters
    "schemesHeaderTitle" to "5 ଟି ଏକୀକୃତ ଜନଜାତି ଯୋଜନା",
    "schemesHeaderSubtitle" to "ଜନଜାତି ବ୍ୟାପାର ମନ୍ତ୍ରଣାଳୟର ସରକାରୀ ଛାତ୍ରବୃତ୍ତି କାଟାଲଗ୍",
    "filterAll" to "ସମସ୍ତ ଯୋଜନା (5)",
    "filterPreMatric" to "ପ୍ରି-ମାଟ୍ରିକ",
    "filterPostMatric" to "ପୋଷ୍ଟ-ମାଟ୍ରିକ",
    "filterTopClass" to "ଟପ୍ କ୍ଲାସ୍",
    "filterFellowship" to "NFST ଫେଲୋସିପ୍",
    "filterOverseas" to "ଜାତୀୟ ଓଭରସିଜ୍",
    "filterEligible" to "ଯୋଗ୍ୟ",
    "filterApplied" to "ଆବେଦିତ",
    "filterNeedsAttention" to "ପଦକ୍ଷେପ ଆବଶ୍ୟକ",
    "filterNeedsAction" to "ପଦକ୍ଷେପ ଆବଶ୍ୟକ",
    "filterApproved" to "ଅନୁମୋଦିତ",
    "filterInProgress" to "ପ୍ରକ୍ରିୟାଧୀନ",
    "matchScoreLabel" to "ଯୋଗ୍ୟତା: %1\$d%%",
    "grantAmountLabel" to "ଅନୁଦାନ ରାଶି",
    "deadlineLabel" to "ଶେଷ ତାରିଖ",
    "deadlineDate" to "ଶେଷ ତାରିଖ ପୂର୍ବରୁ ଆବେଦନ କରନ୍ତୁ",
    "eligibilityCheckPassed" to "ଯୋଗ୍ୟତା ପ୍ରମାଣିତ",
    "noSchemesFound" to "ମନୋନୀତ ଫିଲ୍ଟର୍ ପାଇଁ କୌଣସି ଯୋଜନା ମିଳିଲା ନାହିଁ।",

    // Scheme Detail Screen
    "schemeOverviewTitle" to "ଯୋଜନାର ସଂକ୍ଷିପ୍ତ ବିବରଣୀ ଓ ନିୟମାବଳୀ",
    "statutoryBenefitsTitle" to "ଆର୍ଥିକ ଲାଭ",
    "eligibilityCriteriaTitle" to "ଯୋଗ୍ୟତା ମାନଦଣ୍ଡ",
    "requiredDocumentsTitle" to "ଆବଶ୍ୟକ ପ୍ରମାଣିତ କାଗଜପତ୍ର",
    "verificationAuthorityTitle" to "ମଞ୍ଜୁରୀ କର୍ତ୍ତୃପକ୍ଷ",
    "singleWindowNotice" to "ଏକକ ୱିଣ୍ଡୋ ପ୍ରତ୍ୟକ୍ଷ ଲାଭ ହସ୍ତାନ୍ତର (ଆଧାର ଆକ୍ଟ ଧାରା 7 ଅନୁଯାୟୀ)",
    "oneClickApplyBanner" to "ଡିଜିଲକର ଓ ଅପାର ରେଜିଷ୍ଟ୍ରିରୁ ସ୍ୱତଃ ପୂରଣ ହୋଇଛି। କୌଣସି ମାନୁଆଲ ଅପଲୋଡ୍ ଆବଶ୍ୟକ ନାହିଁ।",
    "trackStatusTab" to "ସ୍ଥିତି ଟ୍ରାକ୍ କରନ୍ତୁ",
    "noDisbursementsFound" to "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଅର୍ଥ ପ୍ରଦାନ କରାଯାଇ ନାହିଁ",

    // Scholarship Wizard Modal
    "wizardTitle" to "1-କ୍ଲିକ୍ ଛାତ୍ରବୃତ୍ତି ଆବେଦନ",
    "wizardStep1Title" to "ଛାତ୍ର ଓ ଶିକ୍ଷାଗତ ଯାଞ୍ଚ",
    "wizardStep1Subtitle" to "AISHE ଏବଂ APAAR ପଞ୍ଜିକରଣରୁ ପ୍ରାପ୍ତ",
    "wizardStep2Title" to "ପାରିବାରିକ ଓ ଆୟ ଘୋଷଣା",
    "wizardStep2Subtitle" to "ରାଜ୍ୟ ଇ-ଡିଷ୍ଟ୍ରିକ୍ଟ ପ୍ରମାଣପତ୍ରରୁ ସତ୍ୟାପିତ",
    "wizardStep3Title" to "ଡିଜିଲକର ଦସ୍ତାବେଜ୍ ଯାଞ୍ଚ",
    "wizardStep3Subtitle" to "କ୍ରିପ୍ଟୋଗ୍ରାଫିକ ଡିଜିଟାଲ ମୋହର ଦ୍ୱାରା ପ୍ରମାଣିତ",
    "wizardStep4Title" to "ସମୀକ୍ଷା ଓ PFMS କୁ ଦାଖଲ",
    "wizardStep4Subtitle" to "ଆଧାର ଆକ୍ଟ ଧାରା 7 ଅନୁଯାୟୀ ସମ୍ମତି",
    "wizardIncomePrompt" to "ଆପଣଙ୍କ ପାରିବାରିକ ବାର୍ଷିକ ଆୟ ନିଶ୍ଚିତ କରନ୍ତୁ (₹):",
    "wizardDocFetchSuccess" to "%1\$s ଡିଜିଲକର ଦ୍ୱାରା ପ୍ରମାଣିତ ଓ ସଂଯୁକ୍ତ।",
    "wizardDpdpConsentPrompt" to "ମୁଁ DPDP ଆକ୍ଟ 2023 ଅନୁଯାୟୀ ସ୍ୱତଃ ଯାଞ୍ଚ ପାଇଁ ସମ୍ମତି ଦେଉଛି।",
    "wizardSubmitting" to "ଆବେଦନ ମନ୍ତ୍ରଣାଳୟ ପୋର୍ଟାଲକୁ ପଠାଯାଉଛି...",
    "wizardSuccessTitle" to "ଆବେଦନ ସଫଳତାର ସହ ଦାଖଲ ହେଲା!",
    "wizardSuccessDesc" to "ଆବେଦନ ଆଇଡି: %1\$s। ଆପଣ ବାସ୍ତବ ସମୟରେ ସ୍ଥିତି ଟ୍ରାକ୍ କରିପାରିବେ।",

    // DigiLocker Wallet Screen & Modal
    "digiLockerWalletTitle" to "ଡିଜିଲକର ଡକ୍ୟୁମେଣ୍ଟ ୱାଲେଟ୍",
    "digiLockerWalletSubtitle" to "କାଗଜବିହୀନ ପୁନଃ ବ୍ୟବହାରଯୋଗ୍ୟ ଡିଜିଟାଲ ପ୍ରମାଣପତ୍ର",
    "digiLockerConnected" to "ଡିଜିଲକର ସଂଯୁକ୍ତ ଅଛି",
    "digiLockerNotConnected" to "ଡିଜିଲକର ସଂଯୁକ୍ତ ନାହିଁ",
    "connectDigiLockerBtn" to "ଡିଜିଲକର ସଂଯୋଗ କରନ୍ତୁ",
    "syncCredentialsBtn" to "ପ୍ରମାଣପତ୍ର ସିଙ୍କ କରନ୍ତୁ",
    "fetchMoreDocsBtn" to "ଅନ୍ୟ ଦସ୍ତାବେଜ୍ ଆଣନ୍ତୁ",
    "zeroPaperworkGuarantee" to "ସମସ୍ତ 5 ଯୋଜନାରେ ପୁନଃ ବ୍ୟବହାରଯୋଗ୍ୟ, ବିନା କୌଣସି ସ୍କାନିଂରେ।",
    "attachedCredentialsTitle" to "ୱାଲେଟରେ ପ୍ରମାଣିତ ଦସ୍ତାବେଜ୍",
    "tapToInspect" to "ଡିଜିଟାଲ ମୋହର ଦେଖିବା ପାଇଁ କାର୍ଡ ଉପରେ ଟ୍ୟାପ୍ କରନ୍ତୁ",
    "reusableBadge" to "5/5 ଯୋଜନାରେ ମାନ୍ୟ",
    "digiLockerModalTitle" to "ଡିଜିଲକର ସମ୍ମତି",
    "digiLockerConsentText" to "ଡିଜିଲକର ଯୋଡ଼ି ଆପଣ ଏକୀକୃତ ପୋର୍ଟାଲକୁ ଆପଣଙ୍କ ସରକାରୀ ପ୍ରମାଣପତ୍ର ପାଇବାକୁ ଅନୁମତି ଦେଉଛନ୍ତି।",
    "digiLockerLinkSuccess" to "ଡିଜିଲକର ୱାଲେଟ୍ ସଫଳତାର ସହ ଲିଙ୍କ୍ ହେଲା।",
    "sealVerifiedText" to "%1\$s ଦ୍ୱାରା %2\$s ରେ ଡିଜିଟାଲ ଭାବେ ପ୍ରମାଣିତ",

    // DBT Disbursement Rail
    "dbtTrackerTitle" to "DBT ପେମେଣ୍ଟ ରେଳ",
    "dbtTrackerSubtitle" to "ଭାରତୀୟ ରିଜର୍ଭ ବ୍ୟାଙ୍କ PFMS ପ୍ରଣାଳୀ ଦ୍ୱାରା ପ୍ରତ୍ୟକ୍ଷ ଲାଭ ହସ୍ତାନ୍ତର",
    "dbtDisbursementsTitle" to "DBT ପେମେଣ୍ଟ ରେଳ",
    "totalDisbursedLabel" to "ମୋଟ ପ୍ରଦତ୍ତ ରାଶି",
    "inPipelineLabel" to "ପ୍ରକ୍ରିୟାଧୀନ",
    "upcomingDisbursementsTitle" to "ଆଗାମୀ ପ୍ରଦାନ",
    "completedDisbursementsTitle" to "ସଫଳ ପେମେଣ୍ଟ",
    "dbtAadhaarSeeded" to "ଆଧାର ସଂଯୁକ୍ତ NPCI ସକ୍ରିୟ",
    "dbtPfmsValidated" to "PFMS ବ୍ୟାଙ୍କ ଖାତା ପ୍ରମାଣିତ",
    "dbtCurrentTrancheTitle" to "ମଞ୍ଜୁର ହୋଇଥିବା ଓ ଆଗାମୀ ଅନୁଦାନ",
    "dbtEstimatedDays" to "~%1\$d ଦିନ ମଧ୍ୟରେ ବ୍ୟାଙ୍କ ଖାତାକୁ",
    "dbtPastTransfersTitle" to "ପାସବୁକ୍ ଓ ପେମେଣ୍ଟ ଇତିହାସ",
    "dbtUtrLabel" to "UTR ରେଫରେନ୍ସ: %1\$s",
    "dbtAccountMaskedLabel" to "ଖାତା ସଂଖ୍ୟା: %1\$s",
    "dbtDirectBenefitGuarantee" to "100% ଛାତ୍ରବୃତ୍ତି ସିଧାସଳଖ ଛାତ୍ରଙ୍କ ଖାତାରେ ଜମା ହୁଏ।",

    // Reviewer Desk (Officer)
    "reviewerTitle" to "ଅଧିକାରୀ ସମୀକ୍ଷା ଡେସ୍କ",
    "reviewerSubtitle" to "ଜିଲ୍ଲା ଜନଜାତି ମଙ୍ଗଳ ଅଧିକାରୀ ଡେସ୍କ #4 • ସୁନ୍ଦରଗଡ଼, ଓଡ଼ିଶା",
    "reviewerDeskTitle" to "ଯାଞ୍ଚ ସମୀକ୍ଷା ଡେସ୍କ",
    "reviewerDeskSubtitle" to "ଜିଲ୍ଲା ଜନଜାତି ମଙ୍ଗଳ ଅଧିକାରୀ ଡେସ୍କ",
    "reviewerQueueAll" to "ସମସ୍ତ ମାମଲା (%1\$d)",
    "reviewerQueuePending" to "ସମୀକ୍ଷାଧୀନ ମାମଲା (%1\$d)",
    "reviewerQueueResolved" to "ସମାଧାନ ହୋଇଥିବା ଅଭିଲେଖ (%1\$d)",
    "reviewerDiscrepancyTitle" to "ପାର୍ଥକ୍ୟ ବିବରଣୀ: %1\$s",
    "reviewerDeclaredValue" to "ଛାତ୍ରଙ୍କ ଦ୍ୱାରା ଘୋଷିତ: %1\$s",
    "reviewerRetrievedValue" to "ରେଜିଷ୍ଟ୍ରି ପୋର୍ଟାଲ ରେକର୍ଡ: %1\$s",
    "reviewerToleranceCheck" to "ପାର୍ଥକ୍ୟ: +%1\$.1f%% (ସର୍ବାଧିକ ସୀମା: ₹2.50L)",
    "reviewerTolerancePassed" to "ସୀମା ମଧ୍ୟରେ ଅଛି (15%% ନିୟମ ଅନୁଯାୟୀ)",
    "reviewerToleranceExceeded" to "ସୀମା ବାହାରେ — ବିସ୍ତୃତ ଯାଞ୍ଚ ଆବଶ୍ୟକ",
    "reviewerApproveBtn" to "ଅନୁମୋଦନ କରନ୍ତୁ",
    "reviewerClarifyBtn" to "ଛାତ୍ରଙ୍କଠାରୁ ସ୍ପଷ୍ଟୀକରଣ ମାଗନ୍ତୁ",
    "reviewerNotesPlaceholder" to "ଅଧିକାରୀଙ୍କ ମନ୍ତବ୍ୟ ଲେଖନ୍ତୁ...",
    "reviewerEmptyQueue" to "ସମସ୍ତ ଯୋଜନା ବିସଙ୍ଗତି ସମାଧାନ ହୋଇସାରିଛି।",

    // Audit Trail & DPDP Compliance
    "auditTrailTitle" to "DPDP ଆକ୍ଟ ଅଡିଟ୍ ଟ୍ରେଲ୍",
    "auditTrailSubtitle" to "ତଥ୍ୟ ପ୍ରବେଶ ଓ ଯାଞ୍ଚର ଟାମ୍ପର-ପ୍ରୁଫ୍ ରେକର୍ଡ",
    "auditTimestampLabel" to "ସମୟ",
    "auditActorLabel" to "ସିଷ୍ଟମ୍ / ଅଧିକାରୀ",
    "auditPurposeLabel" to "ଉଦ୍ଦେଶ୍ୟ",
    "auditHashLabel" to "ଇଣ୍ଟେଗ୍ରିଟି ହ୍ୟାସ୍",
    "dpdpModalTitle" to "ତଥ୍ୟ ସୁରକ୍ଷା ଓ DPDP ଆକ୍ଟ 2023",
    "dpdpModalSubtitle" to "ଭାରତୀୟ ଆଇନ ଅଧୀନରେ ଆପଣଙ୍କ ମୌଳିକ ତଥ୍ୟ ଗୋପନୀୟତା ଅଧିକାର",
    "dpdpDataMinimization" to "ତଥ୍ୟ ସଂକ୍ଷିପ୍ତୀକରଣ: କେବଳ ଆବଶ୍ୟକୀୟ ଯୋଗ୍ୟତା ତଥ୍ୟ ବ୍ୟବହାର କରାଯାଏ।",
    "dpdpPurposeLimitation" to "ଉଦ୍ଦେଶ୍ୟ ସୀମା: ରେକର୍ଡ କେବଳ ଛାତ୍ରବୃତ୍ତି ପ୍ରଦାନ ପାଇଁ ବ୍ୟବହୃତ ହୁଏ।",
    "dpdpConsentRevocation" to "ସମ୍ମତି ପ୍ରତ୍ୟାହାର ଅଧିକାର: ଯେକୌଣସି ସମୟରେ ସମ୍ମତି ପ୍ରତ୍ୟାହାର କରିପାରିବେ।",
    "dpdpRightToErasure" to "ଅଭିଯୋଗ ନିବାରଣ ଅଧିକାର: ତଥ୍ୟ ସୁରକ୍ଷା ବୋର୍ଡ ନିକଟରେ ସିଧାସଳଖ ଅଭିଯୋଗ।",

    // Login & Personas
    "loginTitle" to "ଛାତ୍ର ହିତାଧିକାରୀ ଲଗଇନ୍",
    "loginSubtitle" to "ମୋବାଇଲ୍ ନମ୍ବର ବା ଆଧାର ଦ୍ୱାରା ଏକୀକୃତ ପ୍ରବେଶ",
    "loginMobilePlaceholder" to "10-ଅଙ୍କ ବିଶିଷ୍ଟ ମୋବାଇଲ୍ ବା 12-ଅଙ୍କ ଆଧାର ନମ୍ବର ଦିଅନ୍ତୁ",
    "loginSendOtpBtn" to "OTP ପଠାନ୍ତୁ",
    "loginOtpPlaceholder" to "6-ଅଙ୍କ ବିଶିଷ୍ଟ OTP ଦିଅନ୍ତୁ",
    "loginVerifyBtn" to "ଯାଞ୍ଚ କରନ୍ତୁ ଓ ଛାତ୍ରବୃତ୍ତି ଦେଖନ୍ତୁ",
    "loginMockOtpHire" to "ଡେମୋ ଟେଷ୍ଟ OTP: 123456",
    "loginPersonaQuickPicker" to "କିମ୍ବା ଡେମୋ ଛାତ୍ର ପ୍ରୋଫାଇଲ୍ ବାଛନ୍ତୁ:",
    "loginCustomStudentName" to "ଆପଣଙ୍କ ସମ୍ପୂର୍ଣ୍ଣ ନାମ ଲେଖନ୍ତୁ",
    "loginLoggingIn" to "UIDAI ଓ ଡିଜିଲକରରୁ ଯାଞ୍ଚ ଚାଲିଛି...",

    // App Intro Tour
    "tourStep1Title" to "ଏକୀକୃତ (Ekikrit) କୁ ସ୍ୱାଗତ",
    "tourStep1Desc" to "ଜନଜାତି ବ୍ୟାପାର ମନ୍ତ୍ରଣାଳୟର ସମସ୍ତ 5 ଟି ଛାତ୍ରବୃତ୍ତି ଯୋଜନା ପାଇଁ ଏକକ ୱିଣ୍ଡୋ ଆପ୍।",
    "tourStep2Title" to "କାଗଜବିହୀନ ଡିଜିଲକର ୱାଲେଟ୍",
    "tourStep2Desc" to "ଜାତି, ଆୟ ଓ ମାର୍କସିଟ୍ ଥରେ ଆଣନ୍ତୁ ଏବଂ ସମସ୍ତ ଛାତ୍ରବୃତ୍ତିରେ ବିନା ପୁନଃ ଅପଲୋଡରେ ବ୍ୟବହାର କରନ୍ତୁ।",
    "tourStep3Title" to "ସ୍ୱୟଂକ୍ରିୟ ବହୁ-ପଞ୍ଜିକରଣ ଯାଞ୍ଚ",
    "tourStep3Desc" to "ସାତଟି ଜାତୀୟ ଡାଟାବେସ୍ ଆପଣଙ୍କ ବିବରଣୀର ସ୍ୱତଃ ଯାଞ୍ଚ କରେ। ପାର୍ଥକ୍ୟ ଥିଲେ ମଧ୍ୟ ଆବେଦନ ଅଟକେ ନାହିଁ।",
    "tourStep4Title" to "ସିଧାସଳଖ ବ୍ୟାଙ୍କ ଖାତାରେ DBT ପେମେଣ୍ଟ",
    "tourStep4Desc" to "PFMS ପେମେଣ୍ଟ ମଞ୍ଜୁରୀ ଏବଂ ଆଧାର ସଂଯୁକ୍ତ ବ୍ୟାଙ୍କ ଖାତାରେ ଜମା ହେବାର ରିଅଲ୍-ଟାଇମ୍ ଟ୍ରାକିଂ।",
    "tourMultilingualHonestBadge" to "ହିନ୍ଦୀ, ଓଡ଼ିଆ, ଗୋଣ୍ଡି (ବିଟା) ଏବଂ ଇଂରାଜୀରେ ଅଡିଓ ସହାୟତା ସହ ଉପଲବ୍ଧ।",

    // Notifications & Share
    "notificationsTitle" to "ବିଜ୍ଞପ୍ତି ଓ ସତର୍କତା",
    "notificationsEmpty" to "କୌଣସି ନୂଆ ବିଜ୍ଞପ୍ତି ନାହିଁ",
    "notificationsMarkAllRead" to "ସମସ୍ତ ପଢ଼ା ହୋଇଛି ବୋଲି ଚିହ୍ନିତ କରନ୍ତୁ",
    "shareAppTitle" to "ସାଥୀ ଛାତ୍ରଛାତ୍ରୀଙ୍କ ସହ ଏକୀକୃତ ସେୟାର କରନ୍ତୁ",
    "shareAppSubtitle" to "ଆପଣଙ୍କ ଗାଁ ଓ କଲେଜର ଜନଜାତି ଛାତ୍ରଛାତ୍ରୀଙ୍କୁ ଛାତ୍ରବୃତ୍ତି ପାଇବାରେ ସାହାଯ୍ୟ କରନ୍ତୁ",
    "shareAppCopyLink" to "ଆପ୍ ଲିଙ୍କ୍ କପି କରନ୍ତୁ",
    "shareAppInviteText" to "ଜନଜାତି ବ୍ୟାପାର ମନ୍ତ୍ରଣାଳୟ ଛାତ୍ରବୃତ୍ତି ପାଇଁ ଏକୀକୃତ ଆପ୍ ରେ ସହଜରେ ଆବେଦନ କରନ୍ତୁ: https://ekikrit.tribal.gov.in",

    // JAGO AI Chatbot
    "jagoTitle" to "ଜାଗୋ (JAGO) AI ସହାୟକ",
    "jagoSubtitle" to "ବହୁଭାଷୀ ସ୍ୱର ଓ ଟେକ୍ସଟ୍ ଜନଜାତି ଛାତ୍ରବୃତ୍ତି ମାର୍ଗଦର୍ଶକ",
    "jagoTyping" to "ଜାଗୋ ଭାବୁଛନ୍ତି...",
    "jagoOfflineNotice" to "ଜାଗୋ ବର୍ତ୍ତମାନ ଅଫଲାଇନ୍ ମୋଡରେ କାର୍ଯ୍ୟ କରୁଛି।",
    "jagoInputPlaceholder" to "ହିନ୍ଦୀ, ଓଡ଼ିଆ, ଗୋଣ୍ଡି ବା ଇଂରାଜୀରେ ପଚାରନ୍ତୁ...",
    "askJagoPlaceholder" to "ଜାଗୋଙ୍କୁ ହିନ୍ଦୀ, ଓଡ଼ିଆ, ଗୋଣ୍ଡି ବା ଇଂରାଜୀରେ କିଛି ବି ପଚାରନ୍ତୁ...",
    "jagoSendBtn" to "ପଠାନ୍ତୁ",
    "jagoWelcomeMessage" to "ଜୋହାର! ମୁଁ ଜାଗୋ, ଆପଣଙ୍କ ଜନଜାତି ଛାତ୍ରବୃତ୍ତି ସହାୟକ। ଆଜି ମୁଁ ଆପଣଙ୍କୁ କିପରି ସାହାଯ୍ୟ କରିପାରିବି?",
    "jagoLanguageSwitchOffer" to "ଆପଣ %1\$s ରେ ଲେଖୁଛନ୍ତି। ଆପଣ ଆପ୍ ଭାଷା %2\$s କୁ ବଦଳାଇବାକୁ ଚାହାଁନ୍ତି କି?",
    "jagoSwitchLanguageBtn" to "%1\$s କୁ ବଦଳାନ୍ତୁ",
    "jagoChipStatus" to "ଆବେଦନର ସ୍ଥିତି",
    "jagoChipEligible" to "ମୁଁ କେଉଁ ଯୋଜନା ପାଇଁ ଯୋଗ୍ୟ?",
    "jagoChipDocs" to "ମୋତେ କେଉଁ କାଗଜପତ୍ର ଦରକାର?",
    "jagoChipPayment" to "ମୋ ଛାତ୍ରବୃତ୍ତି କେବେ ଆସିବ?",
    "jagoChipIncomeFlag" to "ମୋ ଆୟ ଯାଞ୍ଚ କାହିଁକି ହେଉଛି?",
    "jagoChipVariance" to "ମୋ ଆୟ ଯାଞ୍ଚ କାହିଁକି ହେଉଛି?",
    "jagoChipApply" to "1-କ୍ଲିକ୍ ରେ କିପରି ଆବେଦନ କରିବେ?",

    // Enums & Statuses Localization
    "stageSubmitted" to "ଆବେଦନ ଦାଖଲ ହେଲା",
    "stageInstituteVerification" to "ଅନୁଷ୍ଠାନ ଯାଞ୍ଚ",
    "stageStateVerification" to "ରାଜ୍ୟ ଯାଞ୍ଚ",
    "stageMinistryReview" to "ମନ୍ତ୍ରଣାଳୟ ମଞ୍ଜୁରୀ",
    "stageSanctioned" to "ଅନୁଦାନ ମଞ୍ଜୁର",
    "stageDisbursed" to "ବ୍ୟାଙ୍କ ଖାତାକୁ ପ୍ରଦାନ କରାଗଲା",
    "stageActionRequired" to "ସମୀକ୍ଷା ଆବଶ୍ୟକ",
    "stageRejected" to "ଖାରଜ",

    "statusVerified" to "ପ୍ରମାଣିତ",
    "statusMismatch" to "ପାର୍ଥକ୍ୟ ଚିହ୍ନିତ",
    "statusPending" to "ଯାଞ୍ଚ ବାକି ଅଛି",
    "statusResolved" to "ଅଧିକାରୀଙ୍କ ଦ୍ୱାରା ସ୍ୱୀକୃତ",
    "statusDiscrepancy" to "ସମୀକ୍ଷାଧୀନ",

    "docAadhaar" to "ଆଧାର କାର୍ଡ",
    "docCaste" to "ଅନୁସୂଚିତ ଜନଜାତି ପ୍ରମାଣପତ୍ର",
    "docIncome" to "ଆୟ ପ୍ରମାଣପତ୍ର",
    "docMarksheet" to "ଶିକ୍ଷାଗତ ମାର୍କସିଟ୍",
    "docDomicile" to "ବାସସ୍ଥାନ ପ୍ରମାଣପତ୍ର",
    "docApaar" to "APAAR / ABC ଆଇଡି କାର୍ଡ",
    "docAdmissionProof" to "ଅନୁଷ୍ଠାନ ନାମଲେଖା ପ୍ରମାଣପତ୍ର",
    "docFeeReceipt" to "ଫିସ ରସିଦ",
    "docBankPassbook" to "ଆଧାର ସଂଯୁକ୍ତ ବ୍ୟାଙ୍କ ପାସବୁକ୍",

    "srcUidai" to "UIDAI ଆଧାର ଭଲ୍ଟ",
    "srcDigilocker" to "ଡିଜିଲକର ଡିଜିଟାଲ ୱାଲେଟ୍",
    "srcAishe" to "AISHE ଉଚ୍ଚଶିକ୍ଷା ପୋର୍ଟାଲ",
    "srcApaar" to "APAAR ଛାତ୍ର ଆଇଡି",
    "srcUdisePlus" to "UDISE+ ବିଦ୍ୟାଳୟ ଡାଟାବେସ୍",
    "srcUgcNta" to "UGC / NTA ପୋର୍ଟାଲ",
    "srcEdistrict" to "ରାଜ୍ୟ ଇ-ଡିଷ୍ଟ୍ରିକ୍ଟ ପୋର୍ଟାଲ",

    // Scheme Name & Desc Overrides
    "schemePreName" to "ଅନୁସୂଚିତ ଜନଜାତି ଛାତ୍ରଛାତ୍ରୀଙ୍କ ପାଇଁ ପ୍ରି-ମାଟ୍ରିକ ଛାତ୍ରବୃତ୍ତି (ଶ୍ରେଣୀ IX ଓ X)",
    "schemePreDesc" to "ମାଧ୍ୟମିକ ବିଦ୍ୟାଳୟରେ ପଢ଼ୁଥିବା ST ଛାତ୍ରଛାତ୍ରୀଙ୍କ ପାଇଁ ବାର୍ଷିକ ₹3,500 ଆର୍ଥିକ ସହାୟତା।",
    "schemePmsName" to "ଅନୁସୂଚିତ ଜନଜାତି ଛାତ୍ରଛାତ୍ରୀଙ୍କ ପାଇଁ ପୋଷ୍ଟ-ମାଟ୍ରିକ ଛାତ୍ରବୃତ୍ତି",
    "schemePmsDesc" to "ଉଚ୍ଚଶିକ୍ଷା ପାଇଁ ସମ୍ପୂର୍ଣ୍ଣ ଟ୍ୟୁସନ ଫିସ୍ ଓ ରହିବା ଖର୍ଚ୍ଚ (ବାର୍ଷିକ ₹20,000 ପର୍ଯ୍ୟନ୍ତ)।",
    "schemeTopClassName" to "ଉଚ୍ଚଶିକ୍ଷା ପାଇଁ ଜାତୀୟ ଫେଲୋସିପ୍ ଓ ଛାତ୍ରବୃତ୍ତି (ଟପ୍ କ୍ଲାସ୍)",
    "schemeTopClassDesc" to "IIT, NIT, IIM, AIIMS ଭଳି ଶୀର୍ଷ ଅନୁଷ୍ଠାନ ପାଇଁ ସମ୍ପୂର୍ଣ୍ଣ ଫିସ୍ ଓ ବାର୍ଷିକ ₹2,00,000 ପର୍ଯ୍ୟନ୍ତ ସହାୟତା।",
    "schemeNfstName" to "ଜନଜାତି ଛାତ୍ରଛାତ୍ରୀଙ୍କ ପାଇଁ ଜାତୀୟ ଫେଲୋସିପ୍ (ଏମ୍.ଫିଲ୍ / ପିଏଚ୍.ଡି)",
    "schemeNfstDesc" to "ପୂର୍ଣ୍ଣକାଳୀନ ଡକ୍ଟରେଟ୍ ଗବେଷକଙ୍କ ପାଇଁ ମାସିକ ₹31,000 ରୁ ₹35,000 ଗବେଷଣା ଫେଲୋସିପ୍।",
    "schemeNosName" to "ଜନଜାତି ପ୍ରାର୍ଥୀଙ୍କ ପାଇଁ ଜାତୀୟ ଓଭରସିଜ୍ ଛାତ୍ରବୃତ୍ତି",
    "schemeNosDesc" to "ବିଶ୍ୱର ଶ୍ରେଷ୍ଠ 500 QS ବିଶ୍ୱବିଦ୍ୟାଳୟରେ ମାଷ୍ଟର୍ସ ଓ ଡକ୍ଟରେଟ୍ ଅଧ୍ୟୟନ ପାଇଁ ସମ୍ପୂର୍ଣ୍ଣ ଆର୍ଥିକ ସହାୟତା।"
))
